-- BS Eğitim Yönetimi — 2026-08-16 canlı constraint baseline

alter table private.finans_v18_edge_ayar add constraint finans_v18_edge_ayar_id_check CHECK (id);
alter table private.finans_v18_edge_ayar add constraint finans_v18_edge_ayar_pkey PRIMARY KEY (id);
alter table public.aylik_snapshotlar add constraint aylik_snapshotlar_ay_check CHECK (ay >= 1 AND ay <= 12);
alter table public.aylik_snapshotlar add constraint aylik_snapshotlar_ogrenci_id_fkey FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(ogrenci_id);
alter table public.aylik_snapshotlar add constraint aylik_snapshotlar_ogretmen_id_fkey FOREIGN KEY (ogretmen_id) REFERENCES ogretmenler(ogretmen_id);
alter table public.aylik_snapshotlar add constraint aylik_snapshotlar_pkey PRIMARY KEY (snapshot_id);
alter table public.branslar add constraint fk_branslar_varsayilan_ogretmen FOREIGN KEY (varsayilan_ogretmen_id) REFERENCES ogretmenler(ogretmen_id) ON DELETE RESTRICT;
alter table public.branslar add constraint branslar_pkey PRIMARY KEY (brans_id);
alter table public.dersler add constraint fk_dersler_brans FOREIGN KEY (brans_id) REFERENCES branslar(brans_id) ON DELETE RESTRICT;
alter table public.dersler add constraint fk_dersler_derslik FOREIGN KEY (derslik_id) REFERENCES derslikler(derslik_id) ON DELETE RESTRICT;
alter table public.dersler add constraint fk_dersler_ogrenci FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(ogrenci_id) ON DELETE RESTRICT;
alter table public.dersler add constraint fk_dersler_ogretmen FOREIGN KEY (ogretmen_id) REFERENCES ogretmenler(ogretmen_id) ON DELETE RESTRICT;
alter table public.dersler add constraint fk_dersler_program FOREIGN KEY (program_id) REFERENCES sabit_ders_programi(program_id) ON DELETE RESTRICT;
alter table public.dersler add constraint dersler_pkey PRIMARY KEY (ders_id);
alter table public.derslikler add constraint derslikler_pkey PRIMARY KEY (derslik_id);
alter table public.gider_kategorileri add constraint gider_kategorileri_pkey PRIMARY KEY (kategori_id);
alter table public.giderler add constraint giderler_tutar_check CHECK (tutar > 0::numeric);
alter table public.giderler add constraint giderler_hesap_id_fkey FOREIGN KEY (hesap_id) REFERENCES kasa_hesaplari(hesap_id);
alter table public.giderler add constraint giderler_kategori_id_fkey FOREIGN KEY (kategori_id) REFERENCES gider_kategorileri(kategori_id);
alter table public.giderler add constraint giderler_pkey PRIMARY KEY (gider_id);
alter table public.haftalik_ders_uretimleri add constraint haftalik_ders_uretimleri_pkey PRIMARY KEY (hafta_baslangici);
alter table public.hakedis_donemleri add constraint hakedis_donemleri_pkey PRIMARY KEY (hakedis_donemi_id);
alter table public.kasa_hareketleri add constraint fk_kasa_hareketleri_hesap FOREIGN KEY (hesap_id) REFERENCES kasa_hesaplari(hesap_id) ON DELETE RESTRICT;
alter table public.kasa_hareketleri add constraint fk_kasa_hareketleri_ogrenci FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(ogrenci_id) ON DELETE RESTRICT;
alter table public.kasa_hareketleri add constraint fk_kasa_hareketleri_ogretmen FOREIGN KEY (ogretmen_id) REFERENCES ogretmenler(ogretmen_id) ON DELETE RESTRICT;
alter table public.kasa_hareketleri add constraint kasa_hareketleri_pkey PRIMARY KEY (hareket_id);
alter table public.kasa_hesaplari add constraint kasa_hesaplari_pkey PRIMARY KEY (hesap_id);
alter table public.krediler add constraint krediler_aylik_taksit_tutari_check CHECK (aylik_taksit_tutari IS NULL OR aylik_taksit_tutari >= 0::numeric);
alter table public.krediler add constraint krediler_odenen_taksit_check CHECK (odenen_taksit IS NULL OR odenen_taksit >= 0);
alter table public.krediler add constraint krediler_toplam_taksit_check CHECK (toplam_taksit IS NULL OR toplam_taksit >= 0);
alter table public.krediler add constraint krediler_pkey PRIMARY KEY (kredi_id);
alter table public.kullanici_profilleri add constraint kullanici_profilleri_rol_check CHECK (rol = ANY (ARRAY['Yönetici'::text, 'Personel'::text, 'Öğretmen'::text]));
alter table public.kullanici_profilleri add constraint fk_kullanici_profilleri_ogretmen FOREIGN KEY (ogretmen_id) REFERENCES ogretmenler(ogretmen_id) ON DELETE RESTRICT;
alter table public.kullanici_profilleri add constraint kullanici_profilleri_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
alter table public.kullanici_profilleri add constraint kullanici_profilleri_pkey PRIMARY KEY (auth_user_id);
alter table public.kullanici_profilleri add constraint kullanici_profilleri_email_key UNIQUE (email);
alter table public.odevler add constraint fk_odevler_ders FOREIGN KEY (ders_id) REFERENCES dersler(ders_id) ON DELETE RESTRICT;
alter table public.odevler add constraint fk_odevler_ogrenci FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(ogrenci_id) ON DELETE RESTRICT;
alter table public.odevler add constraint fk_odevler_ogretmen FOREIGN KEY (ogretmen_id) REFERENCES ogretmenler(ogretmen_id) ON DELETE RESTRICT;
alter table public.odevler add constraint odevler_pkey PRIMARY KEY (odev_id);
alter table public.ogrenciler add constraint ogrenciler_pkey PRIMARY KEY (ogrenci_id);
alter table public.ogretmen_branslari add constraint ogretmen_branslari_pkey PRIMARY KEY (ogretmen_id, brans_id);
alter table public.ogretmen_odemeleri add constraint fk_ogretmen_odemeleri_donem FOREIGN KEY (hakedis_donemi_id) REFERENCES hakedis_donemleri(hakedis_donemi_id) ON DELETE RESTRICT;
alter table public.ogretmen_odemeleri add constraint fk_ogretmen_odemeleri_hesap FOREIGN KEY (hesap_id) REFERENCES kasa_hesaplari(hesap_id) ON DELETE RESTRICT;
alter table public.ogretmen_odemeleri add constraint fk_ogretmen_odemeleri_kasa_hareketi FOREIGN KEY (kasa_hareket_id) REFERENCES kasa_hareketleri(hareket_id) ON DELETE RESTRICT;
alter table public.ogretmen_odemeleri add constraint fk_ogretmen_odemeleri_ogretmen FOREIGN KEY (ogretmen_id) REFERENCES ogretmenler(ogretmen_id) ON DELETE RESTRICT;
alter table public.ogretmen_odemeleri add constraint ogretmen_odemeleri_pkey PRIMARY KEY (ogretmen_odeme_id);
alter table public.ogretmenler add constraint ogretmenler_pkey PRIMARY KEY (ogretmen_id);
alter table public.rapor_talepleri add constraint rapor_talepleri_ogrenci_id_fkey FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(ogrenci_id);
alter table public.rapor_talepleri add constraint rapor_talepleri_ogretmen_id_fkey FOREIGN KEY (ogretmen_id) REFERENCES ogretmenler(ogretmen_id);
alter table public.rapor_talepleri add constraint rapor_talepleri_pkey PRIMARY KEY (rapor_talep_id);
alter table public.sabit_ders_programi add constraint sabit_ders_programi_tekrar_sikligi_ck CHECK (tekrar_sikligi = ANY (ARRAY['Her Hafta'::text, '2 Haftada Bir'::text, 'Ayda Bir'::text]));
alter table public.sabit_ders_programi add constraint fk_sabit_program_brans FOREIGN KEY (brans_id) REFERENCES branslar(brans_id) ON DELETE RESTRICT;
alter table public.sabit_ders_programi add constraint fk_sabit_program_derslik FOREIGN KEY (derslik_id) REFERENCES derslikler(derslik_id) ON DELETE RESTRICT;
alter table public.sabit_ders_programi add constraint fk_sabit_program_ogrenci FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(ogrenci_id) ON DELETE RESTRICT;
alter table public.sabit_ders_programi add constraint fk_sabit_program_ogretmen FOREIGN KEY (ogretmen_id) REFERENCES ogretmenler(ogretmen_id) ON DELETE RESTRICT;
alter table public.sabit_ders_programi add constraint sabit_ders_programi_pkey PRIMARY KEY (program_id);
alter table public.sabit_program_istisnalari add constraint sabit_program_istisnalari_tur_check CHECK (tur = ANY (ARRAY['Atla'::text, 'Taşı'::text]));
alter table public.sabit_program_istisnalari add constraint sabit_program_istisnalari_orijinal_ders_id_fkey FOREIGN KEY (orijinal_ders_id) REFERENCES dersler(ders_id) ON DELETE SET NULL;
alter table public.sabit_program_istisnalari add constraint sabit_program_istisnalari_program_id_fkey FOREIGN KEY (program_id) REFERENCES sabit_ders_programi(program_id) ON DELETE RESTRICT;
alter table public.sabit_program_istisnalari add constraint sabit_program_istisnalari_yeni_ders_id_fkey FOREIGN KEY (yeni_ders_id) REFERENCES dersler(ders_id) ON DELETE SET NULL;
alter table public.sabit_program_istisnalari add constraint sabit_program_istisnalari_pkey PRIMARY KEY (istisna_id);
alter table public.tahsilatlar add constraint fk_tahsilatlar_hesap FOREIGN KEY (hesap_id) REFERENCES kasa_hesaplari(hesap_id) ON DELETE RESTRICT;
alter table public.tahsilatlar add constraint fk_tahsilatlar_ogrenci FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(ogrenci_id) ON DELETE RESTRICT;
alter table public.tahsilatlar add constraint tahsilatlar_pkey PRIMARY KEY (tahsilat_id);
alter table public.tarifeler add constraint tarifeler_brans_id_fkey FOREIGN KEY (brans_id) REFERENCES branslar(brans_id);
alter table public.tarifeler add constraint tarifeler_ogrenci_id_fkey FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(ogrenci_id);
alter table public.tarifeler add constraint tarifeler_ogretmen_id_fkey FOREIGN KEY (ogretmen_id) REFERENCES ogretmenler(ogretmen_id);
alter table public.tarifeler add constraint tarifeler_pkey PRIMARY KEY (tarife_id);
