-- BS Eğitim Yönetimi — 2026-08-16 canlı index baseline

CREATE INDEX aylik_snapshotlar_ogrenci_idx ON public.aylik_snapshotlar USING btree (ogrenci_id);
CREATE INDEX aylik_snapshotlar_ogretmen_idx ON public.aylik_snapshotlar USING btree (ogretmen_id);
CREATE INDEX aylik_snapshotlar_yil_ay_idx ON public.aylik_snapshotlar USING btree (yil, ay);
CREATE INDEX idx_branslar_varsayilan_ogretmen ON public.branslar USING btree (varsayilan_ogretmen_id);
CREATE INDEX idx_dersler_brans ON public.dersler USING btree (brans_id);
CREATE INDEX idx_dersler_derslik ON public.dersler USING btree (derslik_id);
CREATE INDEX idx_dersler_durum ON public.dersler USING btree (ders_durumu);
CREATE INDEX idx_dersler_ogrenci ON public.dersler USING btree (ogrenci_id);
CREATE INDEX idx_dersler_ogretmen ON public.dersler USING btree (ogretmen_id);
CREATE INDEX idx_dersler_program ON public.dersler USING btree (program_id);
CREATE INDEX idx_dersler_tarih ON public.dersler USING btree (tarih);
CREATE UNIQUE INDEX ux_dersler_program_tarih ON public.dersler USING btree (program_id, tarih) WHERE (program_id IS NOT NULL);
CREATE INDEX idx_gider_kategorileri_aktif ON public.gider_kategorileri USING btree (aktif);
CREATE INDEX idx_gider_kategorileri_grup ON public.gider_kategorileri USING btree (grup);
CREATE INDEX idx_gider_kategorileri_sira ON public.gider_kategorileri USING btree (sira_no);
CREATE INDEX giderler_hesap_idx ON public.giderler USING btree (hesap_id);
CREATE INDEX giderler_kategori_idx ON public.giderler USING btree (kategori_id);
CREATE INDEX giderler_tarih_idx ON public.giderler USING btree (tarih DESC);
CREATE INDEX idx_hakedis_donemleri_aktif ON public.hakedis_donemleri USING btree (aktif);
CREATE INDEX idx_hakedis_donemleri_tarih ON public.hakedis_donemleri USING btree (baslangic_tarihi, bitis_tarihi);
CREATE INDEX idx_kasa_hareketleri_hesap ON public.kasa_hareketleri USING btree (hesap_id);
CREATE INDEX idx_kasa_hareketleri_kaynak ON public.kasa_hareketleri USING btree (kaynak_turu, kaynak_id);
CREATE INDEX idx_kasa_hareketleri_ogrenci ON public.kasa_hareketleri USING btree (ogrenci_id);
CREATE INDEX idx_kasa_hareketleri_ogretmen ON public.kasa_hareketleri USING btree (ogretmen_id);
CREATE INDEX idx_kasa_hareketleri_tarih ON public.kasa_hareketleri USING btree (tarih);
CREATE INDEX idx_kasa_hareketleri_tur ON public.kasa_hareketleri USING btree (hareket_turu);
CREATE INDEX idx_kasa_hesaplari_aktif ON public.kasa_hesaplari USING btree (aktif);
CREATE INDEX idx_kasa_hesaplari_tur ON public.kasa_hesaplari USING btree (hesap_turu);
CREATE INDEX krediler_aktif_idx ON public.krediler USING btree (aktif);
CREATE INDEX idx_kullanici_profilleri_aktif ON public.kullanici_profilleri USING btree (aktif);
CREATE INDEX idx_kullanici_profilleri_ogretmen ON public.kullanici_profilleri USING btree (ogretmen_id);
CREATE INDEX idx_kullanici_profilleri_rol ON public.kullanici_profilleri USING btree (rol);
CREATE INDEX idx_odevler_ders ON public.odevler USING btree (ders_id);
CREATE INDEX idx_odevler_durum ON public.odevler USING btree (durum);
CREATE INDEX idx_odevler_ogrenci ON public.odevler USING btree (ogrenci_id);
CREATE INDEX idx_odevler_ogretmen ON public.odevler USING btree (ogretmen_id);
CREATE INDEX idx_odevler_son_teslim_tarihi ON public.odevler USING btree (son_teslim_tarihi);
CREATE INDEX idx_odevler_verilis_tarihi ON public.odevler USING btree (verilis_tarihi);
CREATE INDEX idx_ogretmen_odemeleri_donem ON public.ogretmen_odemeleri USING btree (hakedis_donemi_id);
CREATE INDEX idx_ogretmen_odemeleri_hesap ON public.ogretmen_odemeleri USING btree (hesap_id);
CREATE INDEX idx_ogretmen_odemeleri_kasa_hareket ON public.ogretmen_odemeleri USING btree (kasa_hareket_id);
CREATE INDEX idx_ogretmen_odemeleri_ogretmen ON public.ogretmen_odemeleri USING btree (ogretmen_id);
CREATE INDEX idx_ogretmen_odemeleri_tarih ON public.ogretmen_odemeleri USING btree (tarih);
CREATE INDEX rapor_talepleri_ogrenci_idx ON public.rapor_talepleri USING btree (ogrenci_id);
CREATE INDEX rapor_talepleri_ogretmen_idx ON public.rapor_talepleri USING btree (ogretmen_id);
CREATE INDEX rapor_talepleri_tarih_idx ON public.rapor_talepleri USING btree (rapor_tarihi DESC);
CREATE INDEX idx_sabit_program_brans ON public.sabit_ders_programi USING btree (brans_id);
CREATE INDEX idx_sabit_program_derslik ON public.sabit_ders_programi USING btree (derslik_id);
CREATE INDEX idx_sabit_program_ogrenci ON public.sabit_ders_programi USING btree (ogrenci_id);
CREATE INDEX idx_sabit_program_ogretmen ON public.sabit_ders_programi USING btree (ogretmen_id);
CREATE INDEX ix_sabit_program_istisna_tarih ON public.sabit_program_istisnalari USING btree (orijinal_tarih) WHERE (iptal_mi = false);
CREATE UNIQUE INDEX ux_sabit_program_istisna_aktif ON public.sabit_program_istisnalari USING btree (program_id, orijinal_tarih) WHERE (iptal_mi = false);
CREATE INDEX idx_tahsilatlar_hesap ON public.tahsilatlar USING btree (hesap_id);
CREATE INDEX idx_tahsilatlar_ogrenci ON public.tahsilatlar USING btree (ogrenci_id);
CREATE INDEX idx_tahsilatlar_tarih ON public.tahsilatlar USING btree (tarih);
CREATE INDEX tarifeler_aktif_tarih_idx ON public.tarifeler USING btree (aktif, baslangic_tarihi, bitis_tarihi);
CREATE INDEX tarifeler_brans_idx ON public.tarifeler USING btree (brans_id);
CREATE INDEX tarifeler_ogrenci_idx ON public.tarifeler USING btree (ogrenci_id);
CREATE INDEX tarifeler_ogretmen_idx ON public.tarifeler USING btree (ogretmen_id);
