-- BS Eğitim SaaS V1 — Secondary index katmanı
-- Primary/unique constraint indeksleri 00b içinde oluşur.
-- Koçluk'a ait odev indeksleri Core'a taşınmaz.

create index aylik_snapshotlar_ogrenci_idx on public.aylik_snapshotlar using btree (ogrenci_id);
create index aylik_snapshotlar_ogretmen_idx on public.aylik_snapshotlar using btree (ogretmen_id);
create index aylik_snapshotlar_yil_ay_idx on public.aylik_snapshotlar using btree (yil, ay);
create index bildirim_okumalari_kullanici_idx on public.bildirim_okumalari using btree (auth_user_id, okunma_zamani desc);
create index bildirimler_alici_idx on public.bildirimler using btree (alici_turu, alici_id, olusturulma_zamani desc);
create index bildirimler_kategori_idx on public.bildirimler using btree (kategori, olusturulma_zamani desc);
create index idx_branslar_varsayilan_ogretmen on public.branslar using btree (varsayilan_ogretmen_id);
create index idx_dersler_brans on public.dersler using btree (brans_id);
create index idx_dersler_derslik on public.dersler using btree (derslik_id);
create index idx_dersler_durum on public.dersler using btree (ders_durumu);
create index idx_dersler_ogrenci on public.dersler using btree (ogrenci_id);
create index idx_dersler_ogretmen on public.dersler using btree (ogretmen_id);
create index idx_dersler_program on public.dersler using btree (program_id);
create index idx_dersler_tarih on public.dersler using btree (tarih);
create unique index ux_dersler_program_tarih on public.dersler using btree (program_id, tarih) where program_id is not null;
create index idx_gider_kategorileri_aktif on public.gider_kategorileri using btree (aktif);
create index idx_gider_kategorileri_grup on public.gider_kategorileri using btree (grup);
create index idx_gider_kategorileri_sira on public.gider_kategorileri using btree (sira_no);
create index giderler_hesap_idx on public.giderler using btree (hesap_id);
create index giderler_kategori_idx on public.giderler using btree (kategori_id);
create index giderler_tarih_idx on public.giderler using btree (tarih desc);
create index idx_hakedis_donemleri_aktif on public.hakedis_donemleri using btree (aktif);
create index idx_hakedis_donemleri_tarih on public.hakedis_donemleri using btree (baslangic_tarihi, bitis_tarihi);
create index idx_kasa_hareketleri_hesap on public.kasa_hareketleri using btree (hesap_id);
create index idx_kasa_hareketleri_kaynak on public.kasa_hareketleri using btree (kaynak_turu, kaynak_id);
create index idx_kasa_hareketleri_ogrenci on public.kasa_hareketleri using btree (ogrenci_id);
create index idx_kasa_hareketleri_ogretmen on public.kasa_hareketleri using btree (ogretmen_id);
create index idx_kasa_hareketleri_tarih on public.kasa_hareketleri using btree (tarih);
create index idx_kasa_hareketleri_tur on public.kasa_hareketleri using btree (hareket_turu);
create index idx_kasa_hesaplari_aktif on public.kasa_hesaplari using btree (aktif);
create index idx_kasa_hesaplari_tur on public.kasa_hesaplari using btree (hesap_turu);
create index krediler_aktif_idx on public.krediler using btree (aktif);
create index idx_kullanici_profilleri_aktif on public.kullanici_profilleri using btree (aktif);
create index idx_kullanici_profilleri_ogretmen on public.kullanici_profilleri using btree (ogretmen_id);
create index idx_kullanici_profilleri_rol on public.kullanici_profilleri using btree (rol);
create index idx_odevler_ders on public.odevler using btree (ders_id);
create index idx_odevler_durum on public.odevler using btree (durum);
create index idx_odevler_ogrenci on public.odevler using btree (ogrenci_id);
create index idx_odevler_ogretmen on public.odevler using btree (ogretmen_id);
create index idx_odevler_son_teslim_tarihi on public.odevler using btree (son_teslim_tarihi);
create index idx_odevler_verilis_tarihi on public.odevler using btree (verilis_tarihi);
create index idx_ogretmen_odemeleri_donem on public.ogretmen_odemeleri using btree (hakedis_donemi_id);
create index idx_ogretmen_odemeleri_hesap on public.ogretmen_odemeleri using btree (hesap_id);
create index idx_ogretmen_odemeleri_kasa_hareket on public.ogretmen_odemeleri using btree (kasa_hareket_id);
create index idx_ogretmen_odemeleri_ogretmen on public.ogretmen_odemeleri using btree (ogretmen_id);
create index idx_ogretmen_odemeleri_tarih on public.ogretmen_odemeleri using btree (tarih);
create unique index portal_kullanicilari_ogrenci_uniq on public.portal_kullanicilari using btree (ogrenci_id) where ogrenci_id is not null;
create unique index portal_kullanicilari_ogretmen_uniq on public.portal_kullanicilari using btree (ogretmen_id) where ogretmen_id is not null;
create index rapor_talepleri_ogrenci_idx on public.rapor_talepleri using btree (ogrenci_id);
create index rapor_talepleri_ogretmen_idx on public.rapor_talepleri using btree (ogretmen_id);
create index rapor_talepleri_tarih_idx on public.rapor_talepleri using btree (rapor_tarihi desc);
create index idx_sabit_program_brans on public.sabit_ders_programi using btree (brans_id);
create index idx_sabit_program_derslik on public.sabit_ders_programi using btree (derslik_id);
create index idx_sabit_program_ogrenci on public.sabit_ders_programi using btree (ogrenci_id);
create index idx_sabit_program_ogretmen on public.sabit_ders_programi using btree (ogretmen_id);
create index ix_sabit_program_istisna_tarih on public.sabit_program_istisnalari using btree (orijinal_tarih) where iptal_mi = false;
create unique index ux_sabit_program_istisna_aktif on public.sabit_program_istisnalari using btree (program_id, orijinal_tarih) where iptal_mi = false;
create index idx_tahsilatlar_hesap on public.tahsilatlar using btree (hesap_id);
create index idx_tahsilatlar_ogrenci on public.tahsilatlar using btree (ogrenci_id);
create index idx_tahsilatlar_tarih on public.tahsilatlar using btree (tarih);
create index tarifeler_aktif_tarih_idx on public.tarifeler using btree (aktif, baslangic_tarihi, bitis_tarihi);
create index tarifeler_brans_idx on public.tarifeler using btree (brans_id);
create index tarifeler_ogrenci_idx on public.tarifeler using btree (ogrenci_id);
create index tarifeler_ogretmen_idx on public.tarifeler using btree (ogretmen_id);
