-- BS Eğitim SaaS V1 — Ders ve haftalık üretim RPC paketi

create or replace function public.ders_cakisma_kontrol_v1(p_tarih date,p_ogrenci_id text,p_ogretmen_id text,p_derslik_id text,p_baslangic_saati time without time zone,p_ders_sayisi numeric,p_haric_ders_id text default null::text)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_bas timestamp; v_bit timestamp; v_kapasite integer; v_eszamanli integer:=0; v_ogrenci boolean:=false; v_ogretmen boolean:=false; v_ilk_cakisma jsonb;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if;
  if p_tarih is null or p_baslangic_saati is null then raise exception 'Tarih ve başlangıç saati zorunludur.'; end if;
  if p_ders_sayisi not in (1,2,3,4) then raise exception 'Ders sayısı 1–4 arasında olmalıdır.'; end if;
  select greatest(coalesce(kapasite,1),1) into v_kapasite from public.derslikler where derslik_id=p_derslik_id and coalesce(aktif,true);
  if v_kapasite is null then raise exception 'Aktif derslik bulunamadı.'; end if;
  v_bas:=p_tarih::timestamp+p_baslangic_saati; v_bit:=v_bas+(p_ders_sayisi*interval '1 hour');
  if v_bit::date<>p_tarih then raise exception 'Ders saati gün sınırını aşıyor.'; end if;
  select exists(select 1 from public.dersler d where d.tarih=p_tarih and d.ders_id<>coalesce(p_haric_ders_id,'') and coalesce(d.ders_durumu,'') not in ('İptal','Ertelendi','Öğretmen İptali') and d.baslangic_saati is not null and d.bitis_saati is not null and (p_tarih::timestamp+d.baslangic_saati)<v_bit and v_bas<(p_tarih::timestamp+d.bitis_saati) and d.ogrenci_id=p_ogrenci_id) into v_ogrenci;
  select exists(select 1 from public.dersler d where d.tarih=p_tarih and d.ders_id<>coalesce(p_haric_ders_id,'') and coalesce(d.ders_durumu,'') not in ('İptal','Ertelendi','Öğretmen İptali') and d.baslangic_saati is not null and d.bitis_saati is not null and (p_tarih::timestamp+d.baslangic_saati)<v_bit and v_bas<(p_tarih::timestamp+d.bitis_saati) and d.ogretmen_id=p_ogretmen_id) into v_ogretmen;
  select count(*) into v_eszamanli from public.dersler d where d.tarih=p_tarih and d.derslik_id=p_derslik_id and d.ders_id<>coalesce(p_haric_ders_id,'') and coalesce(d.ders_durumu,'') not in ('İptal','Ertelendi','Öğretmen İptali') and d.baslangic_saati is not null and d.bitis_saati is not null and (p_tarih::timestamp+d.baslangic_saati)<v_bit and v_bas<(p_tarih::timestamp+d.bitis_saati);
  select jsonb_build_object('ders_id',d.ders_id,'ogrenci',coalesce(o.ad_soyad,'—'),'ogretmen',coalesce(t.ad_soyad,'—'),'baslangic',d.baslangic_saati,'bitis',d.bitis_saati) into v_ilk_cakisma from public.dersler d left join public.ogrenciler o on o.ogrenci_id=d.ogrenci_id left join public.ogretmenler t on t.ogretmen_id=d.ogretmen_id where d.tarih=p_tarih and d.ders_id<>coalesce(p_haric_ders_id,'') and coalesce(d.ders_durumu,'') not in ('İptal','Ertelendi','Öğretmen İptali') and d.baslangic_saati is not null and d.bitis_saati is not null and (p_tarih::timestamp+d.baslangic_saati)<v_bit and v_bas<(p_tarih::timestamp+d.bitis_saati) and (d.ogrenci_id=p_ogrenci_id or d.ogretmen_id=p_ogretmen_id or d.derslik_id=p_derslik_id) order by d.baslangic_saati limit 1;
  return jsonb_build_object('basarili',true,'uygun',not v_ogrenci and not v_ogretmen and v_eszamanli<v_kapasite,'ogrenci_cakisma',v_ogrenci,'ogretmen_cakisma',v_ogretmen,'derslik_dolu',v_eszamanli>=v_kapasite,'derslik_kapasite',v_kapasite,'derslik_eszamanli',v_eszamanli,'bitis_saati',v_bit::time,'ilk_cakisma',v_ilk_cakisma);
end;
$function$;

create or replace function public.ders_durumu_guncelle_guvenli_v1(p_ders_id text,p_yeni_durum text,p_aciklama text default null::text)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_email text:=coalesce(auth.jwt()->>'email',auth.uid()::text,'BS Eğitim'); v_eski text;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if;
  if p_yeni_durum not in ('Planlandı','Yapıldı','Öğrenci Gelmedi','İptal','Ertelendi','Öğretmen İptali') then raise exception 'Geçersiz ders durumu.'; end if;
  select ders_durumu into v_eski from public.dersler where ders_id=p_ders_id for update; if not found then raise exception 'Ders bulunamadı.'; end if;
  update public.dersler set ders_durumu=p_yeni_durum,aciklama=coalesce(nullif(trim(coalesce(p_aciklama,'')),''),aciklama),son_degistiren=v_email,son_degistirme_zamani=now() where ders_id=p_ders_id;
  return jsonb_build_object('basarili',true,'ders_id',p_ders_id,'eski_durum',v_eski,'yeni_durum',p_yeni_durum);
end;
$function$;

create or replace function public.ders_guncelle_guvenli_v1(p_ders_id text,p_tarih date,p_ogrenci_id text,p_ogretmen_id text,p_brans_id text,p_derslik_id text,p_baslangic_saati time without time zone,p_ders_sayisi numeric,p_ogrenci_birim_ucreti numeric,p_ogretmen_birim_hakedisi numeric,p_aciklama text default null::text)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_email text:=coalesce(auth.jwt()->>'email',auth.uid()::text,'BS Eğitim'); v_mevcut public.dersler%rowtype; v_bas timestamp; v_bit timestamp; v_kapasite integer; v_eszamanli integer;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if;
  select * into v_mevcut from public.dersler where ders_id=p_ders_id for update; if not found then raise exception 'Ders bulunamadı.'; end if;
  if coalesce(v_mevcut.ders_durumu,'Planlandı')<>'Planlandı' then raise exception 'Yalnız planlanmış dersler düzenlenebilir.'; end if;
  if p_tarih is null or p_baslangic_saati is null then raise exception 'Ders tarihi ve saati zorunludur.'; end if;
  if p_ders_sayisi not in (1,2,3,4) then raise exception 'Ders sayısı 1–4 arasında olmalıdır.'; end if;
  if p_ogrenci_birim_ucreti is null or p_ogrenci_birim_ucreti<0 or p_ogretmen_birim_hakedisi is null or p_ogretmen_birim_hakedisi<0 then raise exception 'Ücret ve hakediş geçerli olmalıdır.'; end if;
  if not exists(select 1 from public.ogrenciler where ogrenci_id=p_ogrenci_id and coalesce(durum,'Aktif')<>'Pasif') then raise exception 'Aktif öğrenci bulunamadı.'; end if;
  if not exists(select 1 from public.ogretmenler where ogretmen_id=p_ogretmen_id and coalesce(durum,'Aktif')<>'Pasif') then raise exception 'Aktif öğretmen bulunamadı.'; end if;
  if not exists(select 1 from public.branslar where brans_id=p_brans_id and coalesce(aktif,true)) then raise exception 'Aktif branş bulunamadı.'; end if;
  if not private.ogretmen_brans_uygun_mu(p_ogretmen_id,p_brans_id) then raise exception 'Seçilen öğretmen bu branş için tanımlı değil.'; end if;
  select greatest(coalesce(kapasite,1),1) into v_kapasite from public.derslikler where derslik_id=p_derslik_id and coalesce(aktif,true); if v_kapasite is null then raise exception 'Aktif derslik bulunamadı.'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('bs_ofis_ders:'||p_tarih::text||':'||p_baslangic_saati::text));
  v_bas:=p_tarih::timestamp+p_baslangic_saati; v_bit:=v_bas+(p_ders_sayisi*interval '1 hour'); if v_bit::date<>p_tarih then raise exception 'Ders saati gün sınırını aşıyor.'; end if;
  if exists(select 1 from public.dersler d where d.ders_id<>p_ders_id and d.tarih=p_tarih and coalesce(d.ders_durumu,'') not in ('İptal','Ertelendi','Öğretmen İptali') and d.baslangic_saati is not null and d.bitis_saati is not null and (p_tarih::timestamp+d.baslangic_saati)<v_bit and v_bas<(p_tarih::timestamp+d.bitis_saati) and (d.ogrenci_id=p_ogrenci_id or d.ogretmen_id=p_ogretmen_id)) then raise exception 'Öğrenci veya öğretmen aynı saatte başka derste.'; end if;
  select count(*) into v_eszamanli from public.dersler d where d.ders_id<>p_ders_id and d.tarih=p_tarih and d.derslik_id=p_derslik_id and coalesce(d.ders_durumu,'') not in ('İptal','Ertelendi','Öğretmen İptali') and d.baslangic_saati is not null and d.bitis_saati is not null and (p_tarih::timestamp+d.baslangic_saati)<v_bit and v_bas<(p_tarih::timestamp+d.bitis_saati); if v_eszamanli>=v_kapasite then raise exception 'Seçilen derslik bu saatte kapasitesine ulaştı.'; end if;
  update public.dersler set tarih=p_tarih,ogrenci_id=p_ogrenci_id,ogretmen_id=p_ogretmen_id,brans_id=p_brans_id,derslik_id=p_derslik_id,ders_sayisi=p_ders_sayisi,ogrenci_birim_ucreti=p_ogrenci_birim_ucreti,ogretmen_birim_hakedisi=p_ogretmen_birim_hakedisi,ogrenci_toplam_tutar=p_ogrenci_birim_ucreti*p_ders_sayisi,ogretmen_toplam_hakedis=p_ogretmen_birim_hakedisi*p_ders_sayisi,baslangic_saati=p_baslangic_saati,bitis_saati=v_bit::time,ders_yeri=(select mekan_adi from public.derslikler where derslik_id=p_derslik_id),aciklama=nullif(trim(coalesce(p_aciklama,'')),''),son_degistiren=v_email,son_degistirme_zamani=now() where ders_id=p_ders_id;
  return jsonb_build_object('basarili',true,'ders_id',p_ders_id,'bitis_saati',v_bit::time,'program_id',v_mevcut.program_id);
end;
$function$;

create or replace function public.ders_kaydet_guvenli_v1(p_ders_id text,p_tarih date,p_ogrenci_id text,p_ogretmen_id text,p_brans_id text,p_derslik_id text,p_baslangic_saati time without time zone,p_ders_sayisi numeric,p_aciklama text default null::text,p_program_id text default null::text,p_ogrenci_birim_ucreti numeric default null::numeric,p_ogretmen_birim_hakedisi numeric default null::numeric)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_uid uuid:=auth.uid(); v_email text:=coalesce(auth.jwt()->>'email',v_uid::text,'BS Eğitim'); v_bas timestamp; v_bit timestamp; v_kapasite integer; v_eszamanli integer; v_kisi_cakisma boolean; v_ogr_ucret numeric:=p_ogrenci_birim_ucreti; v_ogt_ucret numeric:=p_ogretmen_birim_hakedisi; v_program text:=nullif(trim(coalesce(p_program_id,'')),''); v_mevcut public.dersler%rowtype; v_tarife public.sabit_ders_programi%rowtype;
begin
  if v_uid is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if;
  if nullif(trim(p_ders_id),'') is null then raise exception 'Ders kimliği eksik.'; end if; if p_tarih is null or p_baslangic_saati is null then raise exception 'Ders tarihi ve saati zorunludur.'; end if; if nullif(trim(p_ogrenci_id),'') is null or nullif(trim(p_ogretmen_id),'') is null or nullif(trim(p_brans_id),'') is null or nullif(trim(p_derslik_id),'') is null then raise exception 'Ders bilgileri eksik.'; end if; if p_ders_sayisi not in (1,2,3,4) then raise exception 'Ders sayısı 1–4 arasında olmalıdır.'; end if;
  select * into v_mevcut from public.dersler where ders_id=p_ders_id;
  if v_mevcut.ders_id is not null then if v_mevcut.tarih=p_tarih and v_mevcut.ogrenci_id=p_ogrenci_id and v_mevcut.ogretmen_id=p_ogretmen_id and v_mevcut.brans_id=p_brans_id and v_mevcut.derslik_id=p_derslik_id and v_mevcut.baslangic_saati=p_baslangic_saati and v_mevcut.ders_sayisi=p_ders_sayisi then return jsonb_build_object('basarili',true,'tekrar',true,'ders_id',p_ders_id); end if; raise exception 'Aynı ders kimliği farklı bir kayıtta kullanılıyor.'; end if;
  if not exists(select 1 from public.ogrenciler where ogrenci_id=p_ogrenci_id and coalesce(durum,'Aktif')<>'Pasif') then raise exception 'Aktif öğrenci bulunamadı.'; end if; if not exists(select 1 from public.ogretmenler where ogretmen_id=p_ogretmen_id and coalesce(durum,'Aktif')<>'Pasif') then raise exception 'Aktif öğretmen bulunamadı.'; end if; if not exists(select 1 from public.branslar where brans_id=p_brans_id and coalesce(aktif,true)) then raise exception 'Aktif branş bulunamadı.'; end if; if not private.ogretmen_brans_uygun_mu(p_ogretmen_id,p_brans_id) then raise exception 'Seçilen öğretmen bu branş için tanımlı değil.'; end if; if not exists(select 1 from public.derslikler where derslik_id=p_derslik_id and coalesce(aktif,true)) then raise exception 'Aktif derslik bulunamadı.'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('bs_ofis_ders:'||p_tarih::text||':'||p_baslangic_saati::text)); v_bas:=p_tarih::timestamp+p_baslangic_saati; v_bit:=v_bas+(p_ders_sayisi*interval '1 hour'); if v_bit::date<>p_tarih then raise exception 'Ders saati gün sınırını aşıyor.'; end if;
  select exists(select 1 from public.dersler d where d.tarih=p_tarih and coalesce(d.ders_durumu,'') not in ('İptal','Ertelendi','Öğretmen İptali') and d.baslangic_saati is not null and d.bitis_saati is not null and (p_tarih::timestamp+d.baslangic_saati)<v_bit and v_bas<(p_tarih::timestamp+d.bitis_saati) and (d.ogrenci_id=p_ogrenci_id or d.ogretmen_id=p_ogretmen_id)) into v_kisi_cakisma; if v_kisi_cakisma then raise exception 'Öğrenci veya öğretmen aynı saatte başka derste.'; end if;
  select greatest(coalesce(kapasite,1),1) into v_kapasite from public.derslikler where derslik_id=p_derslik_id; select count(*) into v_eszamanli from public.dersler d where d.tarih=p_tarih and d.derslik_id=p_derslik_id and coalesce(d.ders_durumu,'') not in ('İptal','Ertelendi','Öğretmen İptali') and d.baslangic_saati is not null and d.bitis_saati is not null and (p_tarih::timestamp+d.baslangic_saati)<v_bit and v_bas<(p_tarih::timestamp+d.bitis_saati); if v_eszamanli>=v_kapasite then raise exception 'Seçilen derslik bu saatte kapasitesine ulaştı.'; end if;
  if v_program is not null then select * into v_tarife from public.sabit_ders_programi where program_id=v_program limit 1; if v_tarife.program_id is null then raise exception 'Bağlı sabit program bulunamadı.'; end if; elsif v_ogr_ucret is null or v_ogt_ucret is null then select * into v_tarife from public.sabit_ders_programi where ogrenci_id=p_ogrenci_id and ogretmen_id=p_ogretmen_id and brans_id=p_brans_id and program_durumu='Aktif' order by coalesce(bitis_tarihi,'9999-12-31'::date) desc,coalesce(baslangic_tarihi,'1900-01-01'::date) desc limit 1; end if;
  v_ogr_ucret:=coalesce(v_ogr_ucret,v_tarife.ogrenci_birim_ucreti); v_ogt_ucret:=coalesce(v_ogt_ucret,v_tarife.ogretmen_birim_hakedisi); if v_ogr_ucret is null or v_ogt_ucret is null then raise exception 'Bu ders için öğrenci ücreti veya öğretmen hakedişi bulunamadı.'; end if;
  insert into public.dersler(ders_id,program_id,tarih,ogrenci_id,ogretmen_id,brans_id,derslik_id,ders_sayisi,ogrenci_birim_ucreti,ogretmen_birim_hakedisi,ogrenci_toplam_tutar,ogretmen_toplam_hakedis,ders_durumu,aciklama,olusturan,olusturulma_zamani,baslangic_saati,bitis_saati,ders_turu,ders_yeri) values(p_ders_id,v_program,p_tarih,p_ogrenci_id,p_ogretmen_id,p_brans_id,p_derslik_id,p_ders_sayisi,v_ogr_ucret,v_ogt_ucret,v_ogr_ucret*p_ders_sayisi,v_ogt_ucret*p_ders_sayisi,'Planlandı',nullif(trim(coalesce(p_aciklama,'')),''),v_email,now(),p_baslangic_saati,v_bit::time,'Manuel',(select mekan_adi from public.derslikler where derslik_id=p_derslik_id));
  return jsonb_build_object('basarili',true,'tekrar',false,'ders_id',p_ders_id,'bitis_saati',v_bit::time,'ogrenci_birim_ucreti',v_ogr_ucret,'ogretmen_birim_hakedisi',v_ogt_ucret);
end;
$function$;

-- Hafta üretim durum ve hazırlama fonksiyonları çalışan V3/V6 mantığını korur.
create or replace function public.haftalik_ders_uretim_durumu_v3(p_hafta_baslangici date)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_simdi timestamp without time zone:=pg_catalog.timezone('Europe/Istanbul',pg_catalog.now()); v_mevcut_hafta date:=pg_catalog.date_trunc('week',pg_catalog.timezone('Europe/Istanbul',pg_catalog.now()))::date; v_tarih date; v_offset integer; v_beklenen integer:=0; v_hazir integer:=0; v_eksik integer:=0; v_degismis integer:=0; v_korunan integer:=0; v_fazla integer:=0; v_adet integer; v_ders public.dersler%rowtype; r record;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if; if p_hafta_baslangici is null or extract(isodow from p_hafta_baslangici)<>1 then raise exception 'Hafta başlangıcı Pazartesi olmalıdır.'; end if;
  if p_hafta_baslangici<v_mevcut_hafta then return jsonb_build_object('calisti',true,'gecmis_hafta',true,'guncel_hafta',false,'gecis_kilidi',true,'hafta_baslangici',p_hafta_baslangici,'beklenen',0,'mevcut',0,'hazir',0,'eksik',0,'degismis',0,'korunan',0,'fazla',0); end if;
  for r in select p.* from public.sabit_ders_programi p where p.program_durumu='Aktif' and (p.baslangic_tarihi is null or p.baslangic_tarihi<=p_hafta_baslangici+6) and (p.bitis_tarihi is null or p.bitis_tarihi>=p_hafta_baslangici) order by p.program_id loop
    v_offset:=case r.haftanin_gunu when 'Pazartesi' then 0 when 'Salı' then 1 when 'Çarşamba' then 2 when 'Perşembe' then 3 when 'Cuma' then 4 when 'Cumartesi' then 5 when 'Pazar' then 6 else null end; if v_offset is null then continue; end if; v_tarih:=p_hafta_baslangici+v_offset;
    if not private.sabit_program_tarih_uygun_mu(r.program_id,v_tarih) then continue; end if; if p_hafta_baslangici=v_mevcut_hafta and (v_tarih<v_simdi::date or (v_tarih=v_simdi::date and r.baslangic_saati<=v_simdi::time)) then continue; end if; if exists(select 1 from public.sabit_program_istisnalari i where i.program_id=r.program_id and i.orijinal_tarih=v_tarih and i.iptal_mi=false) then continue; end if;
    v_beklenen:=v_beklenen+1;
    if exists(select 1 from public.dersler d where d.program_id=r.program_id and pg_catalog.date_trunc('week',d.tarih::timestamp)::date=p_hafta_baslangici and (coalesce(d.ders_durumu,'Planlandı')<>'Planlandı' or (p_hafta_baslangici=v_mevcut_hafta and d.tarih::timestamp+coalesce(d.baslangic_saati,'00:00'::time)<=v_simdi))) then v_korunan:=v_korunan+1; continue; end if;
    select count(*) into v_adet from public.dersler d where d.program_id=r.program_id and pg_catalog.date_trunc('week',d.tarih::timestamp)::date=p_hafta_baslangici and coalesce(d.ders_durumu,'Planlandı')='Planlandı' and not exists(select 1 from public.sabit_program_istisnalari i where i.program_id=r.program_id and i.iptal_mi=false and (i.orijinal_tarih=d.tarih or i.orijinal_ders_id=d.ders_id or i.yeni_ders_id=d.ders_id));
    if v_adet>1 then v_fazla:=v_fazla+(v_adet-1); v_degismis:=v_degismis+1; continue; end if; if v_adet=0 then v_eksik:=v_eksik+1; continue; end if;
    select d.* into v_ders from public.dersler d where d.program_id=r.program_id and pg_catalog.date_trunc('week',d.tarih::timestamp)::date=p_hafta_baslangici and coalesce(d.ders_durumu,'Planlandı')='Planlandı' and not exists(select 1 from public.sabit_program_istisnalari i where i.program_id=r.program_id and i.iptal_mi=false and (i.orijinal_tarih=d.tarih or i.orijinal_ders_id=d.ders_id or i.yeni_ders_id=d.ders_id)) order by d.tarih,d.baslangic_saati,d.ders_id limit 1;
    if v_ders.tarih=v_tarih and v_ders.ogrenci_id is not distinct from r.ogrenci_id and v_ders.ogretmen_id is not distinct from r.ogretmen_id and v_ders.brans_id is not distinct from r.brans_id and v_ders.derslik_id is not distinct from r.derslik_id and v_ders.baslangic_saati is not distinct from r.baslangic_saati and v_ders.ders_sayisi is not distinct from r.ders_sayisi and coalesce(v_ders.ogrenci_birim_ucreti,0)=coalesce(r.ogrenci_birim_ucreti,0) and coalesce(v_ders.ogretmen_birim_hakedisi,0)=coalesce(r.ogretmen_birim_hakedisi,0) then v_hazir:=v_hazir+1; else v_degismis:=v_degismis+1; end if;
  end loop;
  return jsonb_build_object('calisti',v_eksik=0 and v_degismis=0 and v_fazla=0,'gecmis_hafta',false,'guncel_hafta',p_hafta_baslangici=v_mevcut_hafta,'gecis_kilidi',v_eksik=0 and v_degismis=0 and v_fazla=0,'hafta_baslangici',p_hafta_baslangici,'beklenen',v_beklenen,'mevcut',v_hazir+v_korunan,'hazir',v_hazir,'eksik',v_eksik,'degismis',v_degismis,'korunan',v_korunan,'fazla',v_fazla);
end;
$function$;

create or replace function public.haftalik_dersleri_hazirla_guvenli_v6(p_hafta_baslangici date)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_uid uuid:=auth.uid(); v_email text:=coalesce(auth.jwt()->>'email',v_uid::text,'BS Eğitim'); v_simdi timestamp without time zone:=pg_catalog.timezone('Europe/Istanbul',pg_catalog.now()); v_mevcut_hafta date:=pg_catalog.date_trunc('week',pg_catalog.timezone('Europe/Istanbul',pg_catalog.now()))::date; v_tarih date; v_offset integer; v_bit timestamp; v_mekan_adi text; v_ders_id text; v_adet integer; v_olusturulan integer:=0; v_guncellenen integer:=0; v_zaten integer:=0; v_korunan integer:=0; v_istisna integer:=0; v_gecmis integer:=0; v_kontrol jsonb; v_durum jsonb; v_ders public.dersler%rowtype; r record;
begin
  if v_uid is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if; if p_hafta_baslangici is null or extract(isodow from p_hafta_baslangici)<>1 then raise exception 'Hafta başlangıcı Pazartesi olmalıdır.'; end if; if p_hafta_baslangici<v_mevcut_hafta then raise exception 'Geçmiş haftalar hazırlanamaz.'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('bs_ofis_manuel_hafta_v6:'||p_hafta_baslangici::text));
  for r in select p.* from public.sabit_ders_programi p where p.program_durumu='Aktif' and (p.baslangic_tarihi is null or p.baslangic_tarihi<=p_hafta_baslangici+6) and (p.bitis_tarihi is null or p.bitis_tarihi>=p_hafta_baslangici) order by p.program_id loop
    v_offset:=case r.haftanin_gunu when 'Pazartesi' then 0 when 'Salı' then 1 when 'Çarşamba' then 2 when 'Perşembe' then 3 when 'Cuma' then 4 when 'Cumartesi' then 5 when 'Pazar' then 6 else null end; if v_offset is null then raise exception 'Sabit programda geçersiz gün var: %',r.program_id; end if; v_tarih:=p_hafta_baslangici+v_offset;
    if not private.sabit_program_tarih_uygun_mu(r.program_id,v_tarih) then continue; end if; if p_hafta_baslangici=v_mevcut_hafta and (v_tarih<v_simdi::date or (v_tarih=v_simdi::date and r.baslangic_saati<=v_simdi::time)) then v_gecmis:=v_gecmis+1; continue; end if; if exists(select 1 from public.sabit_program_istisnalari i where i.program_id=r.program_id and i.orijinal_tarih=v_tarih and i.iptal_mi=false) then v_istisna:=v_istisna+1; continue; end if;
    if r.ogrenci_id is null or r.ogretmen_id is null or r.brans_id is null or r.derslik_id is null or r.baslangic_saati is null or r.ders_sayisi is null or r.ders_sayisi not in (1,2,3,4) then raise exception 'Sabit programda zorunlu ders bilgisi eksik: %',r.program_id; end if;
    if not exists(select 1 from public.ogrenciler o where o.ogrenci_id=r.ogrenci_id and coalesce(o.durum,'Aktif')<>'Pasif') then raise exception 'Sabit program öğrencisi aktif değil: %',r.program_id; end if; if not exists(select 1 from public.ogretmenler o where o.ogretmen_id=r.ogretmen_id and coalesce(o.durum,'Aktif')<>'Pasif') then raise exception 'Sabit program öğretmeni aktif değil: %',r.program_id; end if; if not exists(select 1 from public.branslar b where b.brans_id=r.brans_id and coalesce(b.aktif,true)) then raise exception 'Sabit program branşı aktif değil: %',r.program_id; end if; if not private.ogretmen_brans_uygun_mu(r.ogretmen_id,r.brans_id) then raise exception 'Sabit program öğretmen-branş eşleşmesi geçersiz: %',r.program_id; end if;
    select l.mekan_adi into v_mekan_adi from public.derslikler l where l.derslik_id=r.derslik_id and coalesce(l.aktif,true); if v_mekan_adi is null then raise exception 'Sabit program dersliği aktif değil: %',r.program_id; end if;
    if exists(select 1 from public.dersler d where d.program_id=r.program_id and pg_catalog.date_trunc('week',d.tarih::timestamp)::date=p_hafta_baslangici and (coalesce(d.ders_durumu,'Planlandı')<>'Planlandı' or (p_hafta_baslangici=v_mevcut_hafta and d.tarih::timestamp+coalesce(d.baslangic_saati,'00:00'::time)<=v_simdi))) then v_korunan:=v_korunan+1; continue; end if;
    select count(*) into v_adet from public.dersler d where d.program_id=r.program_id and pg_catalog.date_trunc('week',d.tarih::timestamp)::date=p_hafta_baslangici and coalesce(d.ders_durumu,'Planlandı')='Planlandı' and not exists(select 1 from public.sabit_program_istisnalari i where i.program_id=r.program_id and i.iptal_mi=false and (i.orijinal_tarih=d.tarih or i.orijinal_ders_id=d.ders_id or i.yeni_ders_id=d.ders_id)); if v_adet>1 then raise exception 'Aynı sabit program için bu haftada birden fazla Planlandı ders var (%). Önce bu kayıtları kontrol edin.',r.program_id; end if;
    v_bit:=v_tarih::timestamp+r.baslangic_saati+(r.ders_sayisi*interval '1 hour'); if v_bit::date<>v_tarih then raise exception 'Ders saati gün sınırını aşıyor: %',r.program_id; end if;
    if v_adet=1 then
      select d.* into v_ders from public.dersler d where d.program_id=r.program_id and pg_catalog.date_trunc('week',d.tarih::timestamp)::date=p_hafta_baslangici and coalesce(d.ders_durumu,'Planlandı')='Planlandı' and not exists(select 1 from public.sabit_program_istisnalari i where i.program_id=r.program_id and i.iptal_mi=false and (i.orijinal_tarih=d.tarih or i.orijinal_ders_id=d.ders_id or i.yeni_ders_id=d.ders_id)) order by d.tarih,d.baslangic_saati,d.ders_id limit 1 for update;
      if v_ders.tarih=v_tarih and v_ders.ogrenci_id is not distinct from r.ogrenci_id and v_ders.ogretmen_id is not distinct from r.ogretmen_id and v_ders.brans_id is not distinct from r.brans_id and v_ders.derslik_id is not distinct from r.derslik_id and v_ders.baslangic_saati is not distinct from r.baslangic_saati and v_ders.ders_sayisi is not distinct from r.ders_sayisi and coalesce(v_ders.ogrenci_birim_ucreti,0)=coalesce(r.ogrenci_birim_ucreti,0) and coalesce(v_ders.ogretmen_birim_hakedisi,0)=coalesce(r.ogretmen_birim_hakedisi,0) then v_zaten:=v_zaten+1; continue; end if;
      v_kontrol:=public.ders_cakisma_kontrol_v1(v_tarih,r.ogrenci_id,r.ogretmen_id,r.derslik_id,r.baslangic_saati,r.ders_sayisi,v_ders.ders_id); if not coalesce((v_kontrol->>'uygun')::boolean,false) then raise exception 'Hafta hazırlanamadı: % tarihindeki değişmiş ders yeni gün/saat/derslikte çakışıyor.',v_tarih; end if;
      update public.dersler set tarih=v_tarih,ogrenci_id=r.ogrenci_id,ogretmen_id=r.ogretmen_id,brans_id=r.brans_id,derslik_id=r.derslik_id,ders_sayisi=r.ders_sayisi,ogrenci_birim_ucreti=r.ogrenci_birim_ucreti,ogretmen_birim_hakedisi=r.ogretmen_birim_hakedisi,ogrenci_toplam_tutar=coalesce(r.ogrenci_birim_ucreti,0)*r.ders_sayisi,ogretmen_toplam_hakedis=coalesce(r.ogretmen_birim_hakedisi,0)*r.ders_sayisi,baslangic_saati=r.baslangic_saati,bitis_saati=v_bit::time,ders_yeri=v_mekan_adi,son_degistiren=v_email,son_degistirme_zamani=pg_catalog.now() where ders_id=v_ders.ders_id; v_guncellenen:=v_guncellenen+1; continue;
    end if;
    v_kontrol:=public.ders_cakisma_kontrol_v1(v_tarih,r.ogrenci_id,r.ogretmen_id,r.derslik_id,r.baslangic_saati,r.ders_sayisi,null); if not coalesce((v_kontrol->>'uygun')::boolean,false) then raise exception 'Hafta hazırlanamadı: % tarihindeki yeni ders çakışıyor.',v_tarih; end if;
    loop v_ders_id:=substr(replace(gen_random_uuid()::text,'-',''),1,8); exit when not exists(select 1 from public.dersler d where d.ders_id=v_ders_id); end loop;
    insert into public.dersler(ders_id,program_id,tarih,ogrenci_id,ogretmen_id,brans_id,derslik_id,ders_sayisi,ogrenci_birim_ucreti,ogretmen_birim_hakedisi,ogrenci_toplam_tutar,ogretmen_toplam_hakedis,ders_durumu,baslangic_saati,bitis_saati,ders_yeri,olusturan,olusturulma_zamani) values(v_ders_id,r.program_id,v_tarih,r.ogrenci_id,r.ogretmen_id,r.brans_id,r.derslik_id,r.ders_sayisi,r.ogrenci_birim_ucreti,r.ogretmen_birim_hakedisi,coalesce(r.ogrenci_birim_ucreti,0)*r.ders_sayisi,coalesce(r.ogretmen_birim_hakedisi,0)*r.ders_sayisi,'Planlandı',r.baslangic_saati,v_bit::time,v_mekan_adi,v_email,pg_catalog.now()); v_olusturulan:=v_olusturulan+1;
  end loop;
  v_durum:=public.haftalik_ders_uretim_durumu_v3(p_hafta_baslangici); if not coalesce((v_durum->>'calisti')::boolean,false) then raise exception 'Hafta hazırlama tamamlanamadı: % eksik, % değişmiş kayıt kaldı.',coalesce((v_durum->>'eksik')::integer,0),coalesce((v_durum->>'degismis')::integer,0); end if;
  return jsonb_build_object('basarili',true,'hafta_baslangici',p_hafta_baslangici,'olusturulan',v_olusturulan,'guncellenen',v_guncellenen,'zaten_mevcut',v_zaten,'korunan',v_korunan,'istisna',v_istisna,'gecmis_atlanan',v_gecmis,'durum',v_durum);
end;
$function$;

create or replace function public.haftalik_program_kontrol_oneri_v2(p_hafta_baslangici date)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_simdi timestamp without time zone:=timezone('Europe/Istanbul',now()); v_mevcut_hafta date:=date_trunc('week',timezone('Europe/Istanbul',now()))::date; r record; v_offset integer; v_tarih date; v_kontrol jsonb; v_room_type text; v_room record; v_room_check jsonb; v_saat_offset integer; v_candidate time; v_time_check jsonb; v_rooms jsonb; v_times jsonb; v_issues jsonb:='[]'::jsonb; v_issue_count integer:=0; v_count integer;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if; if p_hafta_baslangici is null or extract(isodow from p_hafta_baslangici)<>1 then raise exception 'Hafta başlangıcı Pazartesi olmalıdır.'; end if; if p_hafta_baslangici<v_mevcut_hafta then return jsonb_build_object('basarili',true,'uygun',true,'hafta_baslangici',p_hafta_baslangici,'sorun_sayisi',0,'sorunlar','[]'::jsonb,'gecmis_hafta',true); end if;
  for r in select p.*,o.ad_soyad as ogrenci_adi,t.ad_soyad as ogretmen_adi,l.mekan_adi,l.mekan_turu from public.sabit_ders_programi p left join public.ogrenciler o on o.ogrenci_id=p.ogrenci_id left join public.ogretmenler t on t.ogretmen_id=p.ogretmen_id left join public.derslikler l on l.derslik_id=p.derslik_id where p.program_durumu='Aktif' order by p.program_id loop
    v_offset:=case r.haftanin_gunu when 'Pazartesi' then 0 when 'Salı' then 1 when 'Çarşamba' then 2 when 'Perşembe' then 3 when 'Cuma' then 4 when 'Cumartesi' then 5 when 'Pazar' then 6 else null end; if v_offset is null then continue; end if; v_tarih:=p_hafta_baslangici+v_offset;
    if not private.sabit_program_tarih_uygun_mu(r.program_id,v_tarih) then continue; end if; if p_hafta_baslangici=v_mevcut_hafta and (v_tarih<v_simdi::date or (v_tarih=v_simdi::date and r.baslangic_saati is not null and r.baslangic_saati<=v_simdi::time)) then continue; end if; if exists(select 1 from public.sabit_program_istisnalari i where i.program_id=r.program_id and i.orijinal_tarih=v_tarih and i.iptal_mi=false) then continue; end if; if exists(select 1 from public.dersler d where d.program_id=r.program_id and d.tarih=v_tarih) then continue; end if;
    v_kontrol:=private.bs_program_tarih_kontrol_v1(r.program_id,v_tarih,r.baslangic_saati,r.derslik_id); if coalesce((v_kontrol->>'uygun')::boolean,false) then continue; end if;
    v_rooms:='[]'::jsonb; v_times:='[]'::jsonb; v_count:=0; v_room_type:=r.mekan_turu;
    for v_room in select d.derslik_id,d.mekan_adi,d.mekan_turu from public.derslikler d where coalesce(d.aktif,true) and d.derslik_id<>r.derslik_id and case when v_room_type='Online' then d.mekan_turu='Online' when v_room_type='Ev' then d.mekan_turu='Ev' else coalesce(d.mekan_turu,'') not in ('Online','Ev') end order by case when d.mekan_turu=v_room_type then 0 else 1 end,d.mekan_adi loop v_room_check:=private.bs_program_tarih_kontrol_v1(r.program_id,v_tarih,r.baslangic_saati,v_room.derslik_id); if coalesce((v_room_check->>'uygun')::boolean,false) then v_rooms:=v_rooms||jsonb_build_array(jsonb_build_object('derslik_id',v_room.derslik_id,'derslik',v_room.mekan_adi,'saat',to_char(r.baslangic_saati,'HH24:MI'))); v_count:=v_count+1; exit when v_count>=3; end if; end loop;
    v_count:=0; foreach v_saat_offset in array array[-1,1,-2,2,-3,3,-4,4,-5,5,-6,6] loop v_candidate:=r.baslangic_saati+(v_saat_offset*interval '30 minutes'); if (date '2000-01-01'+v_candidate+(r.ders_sayisi*interval '1 hour'))::date<>date '2000-01-01' then continue; end if; if p_hafta_baslangici=v_mevcut_hafta and v_tarih=v_simdi::date and v_candidate<=v_simdi::time then continue; end if; v_time_check:=private.bs_program_tarih_kontrol_v1(r.program_id,v_tarih,v_candidate,r.derslik_id); if coalesce((v_time_check->>'uygun')::boolean,false) then v_times:=v_times||jsonb_build_array(jsonb_build_object('saat',to_char(v_candidate,'HH24:MI'),'derslik_id',r.derslik_id,'derslik',r.mekan_adi)); v_count:=v_count+1; else for v_room in select d.derslik_id,d.mekan_adi,d.mekan_turu from public.derslikler d where coalesce(d.aktif,true) and d.derslik_id<>r.derslik_id and case when v_room_type='Online' then d.mekan_turu='Online' when v_room_type='Ev' then d.mekan_turu='Ev' else coalesce(d.mekan_turu,'') not in ('Online','Ev') end order by case when d.mekan_turu=v_room_type then 0 else 1 end,d.mekan_adi loop v_time_check:=private.bs_program_tarih_kontrol_v1(r.program_id,v_tarih,v_candidate,v_room.derslik_id); if coalesce((v_time_check->>'uygun')::boolean,false) then v_times:=v_times||jsonb_build_array(jsonb_build_object('saat',to_char(v_candidate,'HH24:MI'),'derslik_id',v_room.derslik_id,'derslik',v_room.mekan_adi)); v_count:=v_count+1; exit; end if; end loop; end if; exit when v_count>=4; end loop;
    v_issue_count:=v_issue_count+1; v_issues:=v_issues||jsonb_build_array(jsonb_build_object('program_id',r.program_id,'tarih',v_tarih,'ogrenci',coalesce(r.ogrenci_adi,'—'),'ogretmen',coalesce(r.ogretmen_adi,'—'),'saat',to_char(r.baslangic_saati,'HH24:MI'),'derslik_id',r.derslik_id,'derslik',coalesce(r.mekan_adi,'—'),'ogrenci_cakisma',coalesce((v_kontrol->>'ogrenci_cakisma')::boolean,false),'ogretmen_cakisma',coalesce((v_kontrol->>'ogretmen_cakisma')::boolean,false),'derslik_dolu',coalesce((v_kontrol->>'derslik_dolu')::boolean,false),'onerilen_derslikler',v_rooms,'onerilen_saatler',v_times));
  end loop;
  return jsonb_build_object('basarili',true,'uygun',v_issue_count=0,'hafta_baslangici',p_hafta_baslangici,'sorun_sayisi',v_issue_count,'sorunlar',v_issues,'gecmis_hafta',false);
end;
$function$;
