-- BS Eğitim SaaS V1 — Sabit program ve sağlık RPC paketi

create or replace function public.program_saglik_kontrolu_v1()
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_gecersiz_tekrar integer:=0; v_brans_hata integer:=0; v_istisna_hata integer:=0; v_tasima_hata integer:=0; v_cakisma integer:=0; v_kontrol jsonb; r record;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if;
  select count(*) into v_gecersiz_tekrar from public.sabit_ders_programi p where p.program_durumu='Aktif' and (coalesce(p.tekrar_sikligi,'Her Hafta') not in ('Her Hafta','2 Haftada Bir','Ayda Bir') or (coalesce(p.tekrar_sikligi,'Her Hafta')<>'Her Hafta' and p.baslangic_tarihi is null) or (p.bitis_tarihi is not null and p.baslangic_tarihi is not null and p.bitis_tarihi<p.baslangic_tarihi));
  select count(*) into v_brans_hata from public.sabit_ders_programi p where p.program_durumu='Aktif' and not private.ogretmen_brans_uygun_mu(p.ogretmen_id,p.brans_id);
  select count(*) into v_istisna_hata from public.sabit_program_istisnalari i where i.iptal_mi=false and not private.sabit_program_tarih_uygun_mu(i.program_id,i.orijinal_tarih);
  select count(*) into v_tasima_hata from public.sabit_program_istisnalari i where i.iptal_mi=false and i.tur='Taşı' and (i.yeni_ders_id is null or not exists(select 1 from public.dersler d where d.ders_id=i.yeni_ders_id));
  for r in select * from public.sabit_ders_programi where program_durumu='Aktif' loop v_kontrol:=public.sabit_program_cakisma_kontrol_v1(r.ogrenci_id,r.ogretmen_id,r.derslik_id,r.haftanin_gunu,r.baslangic_saati,r.ders_sayisi,coalesce(r.tekrar_sikligi,'Her Hafta'),r.baslangic_tarihi,r.bitis_tarihi,r.program_id); if not coalesce((v_kontrol->>'uygun')::boolean,false) then v_cakisma:=v_cakisma+1; end if; end loop;
  return jsonb_build_object('basarili',(v_gecersiz_tekrar+v_brans_hata+v_istisna_hata+v_tasima_hata+v_cakisma)=0,'toplam_hata',v_gecersiz_tekrar+v_brans_hata+v_istisna_hata+v_tasima_hata+v_cakisma,'gecersiz_tekrar',v_gecersiz_tekrar,'brans_hata',v_brans_hata,'istisna_hata',v_istisna_hata,'tasima_hata',v_tasima_hata,'gelecek_cakisma_programi',v_cakisma,'kontrol_zamani',now());
end;
$function$;

create or replace function public.sabit_program_cakisma_kontrol_v1(p_ogrenci_id text,p_ogretmen_id text,p_derslik_id text,p_haftanin_gunu text,p_baslangic_saati time without time zone,p_ders_sayisi numeric,p_tekrar_sikligi text,p_baslangic_tarihi date,p_bitis_tarihi date,p_haric_program_id text default null::text)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_bas date:=greatest(current_date,coalesce(p_baslangic_tarihi,current_date)); v_son date:=least(coalesce(p_bitis_tarihi,v_bas+370),v_bas+370); v_gun integer; v_kapasite integer; v_ogrenci boolean:=false; v_ogretmen boolean:=false; v_derslik boolean:=false; v_ilk_tarih date; v_ilk_program text; v_ilk_ad text; v_mesaj text:='Çakışma yok.';
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if; if p_baslangic_saati is null then raise exception 'Başlangıç saati zorunludur.'; end if; if p_ders_sayisi not in (1,2,3,4) then raise exception 'Ders sayısı 1–4 arasında olmalıdır.'; end if; if coalesce(p_tekrar_sikligi,'Her Hafta') not in ('Her Hafta','2 Haftada Bir','Ayda Bir') then raise exception 'Geçersiz tekrar sıklığı.'; end if; if coalesce(p_tekrar_sikligi,'Her Hafta')<>'Her Hafta' and p_baslangic_tarihi is null then raise exception 'Bu tekrar sıklığı için başlangıç tarihi zorunludur.'; end if;
  v_gun:=case p_haftanin_gunu when 'Pazartesi' then 1 when 'Salı' then 2 when 'Çarşamba' then 3 when 'Perşembe' then 4 when 'Cuma' then 5 when 'Cumartesi' then 6 when 'Pazar' then 7 else null end; if v_gun is null then raise exception 'Geçersiz gün.'; end if;
  select greatest(coalesce(kapasite,1),1) into v_kapasite from public.derslikler where derslik_id=p_derslik_id and coalesce(aktif,true); if v_kapasite is null then raise exception 'Aktif derslik bulunamadı.'; end if; if v_son<v_bas then return jsonb_build_object('basarili',true,'uygun',true,'mesaj','Programın gelecekte aktif tarihi bulunmuyor.'); end if;
  with aday as (select gs::date tarih,(gs::date::timestamp+p_baslangic_saati) bas,(gs::date::timestamp+p_baslangic_saati+(p_ders_sayisi*interval '1 hour')) bit from generate_series(v_bas::timestamp,v_son::timestamp,interval '1 day') gs where extract(isodow from gs)=v_gun and (p_baslangic_tarihi is null or gs::date>=p_baslangic_tarihi) and (p_bitis_tarihi is null or gs::date<=p_bitis_tarihi) and private.sabit_program_tarihe_duser_mi(coalesce(p_tekrar_sikligi,'Her Hafta'),p_baslangic_tarihi,gs::date)), eslesen as (select a.tarih,p.* from aday a join public.sabit_ders_programi p on p.program_durumu='Aktif' and p.program_id<>coalesce(p_haric_program_id,'') and p.haftanin_gunu=p_haftanin_gunu and (p.baslangic_tarihi is null or a.tarih>=p.baslangic_tarihi) and (p.bitis_tarihi is null or a.tarih<=p.bitis_tarihi) and private.sabit_program_tarihe_duser_mi(p.tekrar_sikligi,p.baslangic_tarihi,a.tarih) where (a.tarih::timestamp+p.baslangic_saati)<a.bit and a.bas<(a.tarih::timestamp+p.baslangic_saati+(coalesce(p.ders_sayisi,1)*interval '1 hour'))) select coalesce(bool_or(ogrenci_id=p_ogrenci_id),false),coalesce(bool_or(ogretmen_id=p_ogretmen_id),false) into v_ogrenci,v_ogretmen from eslesen;
  with aday as (select gs::date tarih,(gs::date::timestamp+p_baslangic_saati) bas,(gs::date::timestamp+p_baslangic_saati+(p_ders_sayisi*interval '1 hour')) bit from generate_series(v_bas::timestamp,v_son::timestamp,interval '1 day') gs where extract(isodow from gs)=v_gun and (p_baslangic_tarihi is null or gs::date>=p_baslangic_tarihi) and (p_bitis_tarihi is null or gs::date<=p_bitis_tarihi) and private.sabit_program_tarihe_duser_mi(coalesce(p_tekrar_sikligi,'Her Hafta'),p_baslangic_tarihi,gs::date)), sayim as (select a.tarih,count(p.program_id) adet from aday a left join public.sabit_ders_programi p on p.program_durumu='Aktif' and p.program_id<>coalesce(p_haric_program_id,'') and p.haftanin_gunu=p_haftanin_gunu and p.derslik_id=p_derslik_id and (p.baslangic_tarihi is null or a.tarih>=p.baslangic_tarihi) and (p.bitis_tarihi is null or a.tarih<=p.bitis_tarihi) and private.sabit_program_tarihe_duser_mi(p.tekrar_sikligi,p.baslangic_tarihi,a.tarih) and (a.tarih::timestamp+p.baslangic_saati)<a.bit and a.bas<(a.tarih::timestamp+p.baslangic_saati+(coalesce(p.ders_sayisi,1)*interval '1 hour')) group by a.tarih) select exists(select 1 from sayim where adet>=v_kapasite) into v_derslik;
  with aday as (select gs::date tarih,(gs::date::timestamp+p_baslangic_saati) bas,(gs::date::timestamp+p_baslangic_saati+(p_ders_sayisi*interval '1 hour')) bit from generate_series(v_bas::timestamp,v_son::timestamp,interval '1 day') gs where extract(isodow from gs)=v_gun and (p_baslangic_tarihi is null or gs::date>=p_baslangic_tarihi) and (p_bitis_tarihi is null or gs::date<=p_bitis_tarihi) and private.sabit_program_tarihe_duser_mi(coalesce(p_tekrar_sikligi,'Her Hafta'),p_baslangic_tarihi,gs::date)), eslesen as (select a.tarih,p.* from aday a join public.sabit_ders_programi p on p.program_durumu='Aktif' and p.program_id<>coalesce(p_haric_program_id,'') and p.haftanin_gunu=p_haftanin_gunu and (p.baslangic_tarihi is null or a.tarih>=p.baslangic_tarihi) and (p.bitis_tarihi is null or a.tarih<=p.bitis_tarihi) and private.sabit_program_tarihe_duser_mi(p.tekrar_sikligi,p.baslangic_tarihi,a.tarih) where (a.tarih::timestamp+p.baslangic_saati)<a.bit and a.bas<(a.tarih::timestamp+p.baslangic_saati+(coalesce(p.ders_sayisi,1)*interval '1 hour')) and (p.ogrenci_id=p_ogrenci_id or p.ogretmen_id=p_ogretmen_id or p.derslik_id=p_derslik_id)) select e.tarih,e.program_id,coalesce(o.ad_soyad,t.ad_soyad,'Sabit program') into v_ilk_tarih,v_ilk_program,v_ilk_ad from eslesen e left join public.ogrenciler o on o.ogrenci_id=e.ogrenci_id left join public.ogretmenler t on t.ogretmen_id=e.ogretmen_id order by e.tarih,e.baslangic_saati limit 1;
  if v_ogrenci then v_mesaj:='Öğrenci seçilen tekrar düzeninde başka sabit dersle çakışıyor.'; elsif v_ogretmen then v_mesaj:='Öğretmen seçilen tekrar düzeninde başka sabit dersle çakışıyor.'; elsif v_derslik then v_mesaj:='Derslik seçilen tekrar düzeninde kapasitesine ulaşıyor.'; end if;
  return jsonb_build_object('basarili',true,'uygun',not v_ogrenci and not v_ogretmen and not v_derslik,'ogrenci_cakisma',v_ogrenci,'ogretmen_cakisma',v_ogretmen,'derslik_dolu',v_derslik,'ilk_cakisma_tarihi',v_ilk_tarih,'ilk_cakisan_program_id',v_ilk_program,'ilk_cakisan_kayit',v_ilk_ad,'mesaj',v_mesaj);
end;
$function$;

create or replace function public.sabit_program_hafta_atla_guvenli_v1(p_program_id text,p_tarih date,p_aciklama text default null::text)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_email text:=coalesce(auth.jwt()->>'email',auth.uid()::text,'BS Eğitim'); v_istisna public.sabit_program_istisnalari%rowtype; v_ders public.dersler%rowtype;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if; if not private.sabit_program_tarih_uygun_mu(p_program_id,p_tarih) then raise exception 'Seçilen tarih bu sabit programın doğal ders tarihi değil.'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('bs_istisna:'||p_program_id||':'||p_tarih::text)); select * into v_istisna from public.sabit_program_istisnalari where program_id=p_program_id and orijinal_tarih=p_tarih and iptal_mi=false limit 1; if found then return jsonb_build_object('basarili',true,'tekrar',true,'istisna_id',v_istisna.istisna_id,'tur',v_istisna.tur); end if;
  select * into v_ders from public.dersler where program_id=p_program_id and tarih=p_tarih order by olusturulma_zamani desc nulls last limit 1 for update; if found and coalesce(v_ders.ders_durumu,'Planlandı') not in ('Planlandı','İptal') then raise exception 'Bu ders artık planlama aşamasında değil; haftayı atlama uygulanamaz.'; end if; if found and coalesce(v_ders.ders_durumu,'Planlandı')='Planlandı' then update public.dersler set ders_durumu='İptal',aciklama=concat_ws(' · ',nullif(aciklama,''),'Sabit program: bu tarih atlandı'),son_degistiren=v_email,son_degistirme_zamani=now() where ders_id=v_ders.ders_id; end if;
  insert into public.sabit_program_istisnalari(program_id,orijinal_tarih,tur,orijinal_ders_id,aciklama,olusturan) values(p_program_id,p_tarih,'Atla',case when found then v_ders.ders_id else null end,nullif(trim(coalesce(p_aciklama,'')),''),v_email) returning * into v_istisna;
  return jsonb_build_object('basarili',true,'tekrar',false,'istisna_id',v_istisna.istisna_id,'tur','Atla','orijinal_ders_id',v_istisna.orijinal_ders_id);
end;
$function$;

create or replace function public.sabit_program_kaydet_guvenli_v4(p_program_id text,p_ogrenci_id text,p_ogretmen_id text,p_brans_id text,p_derslik_id text,p_haftanin_gunu text,p_baslangic_saati time without time zone,p_ders_sayisi numeric,p_ogrenci_birim_ucreti numeric,p_ogretmen_birim_hakedisi numeric,p_tekrar_sikligi text default 'Her Hafta'::text,p_baslangic_tarihi date default null::date,p_bitis_tarihi date default null::date,p_aciklama text default null::text,p_program_durumu text default 'Aktif'::text)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_bas timestamp:=date '2000-01-01'+p_baslangic_saati; v_bit timestamp; v_tekrar text:=coalesce(nullif(trim(p_tekrar_sikligi),''),'Her Hafta'); v_kontrol jsonb; v_program_var_mi boolean:=false;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if; if nullif(trim(p_program_id),'') is null then raise exception 'Program kimliği eksik.'; end if; if p_baslangic_saati is null then raise exception 'Başlangıç saati zorunludur.'; end if; if p_haftanin_gunu not in ('Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar') then raise exception 'Geçersiz gün.'; end if; if p_ders_sayisi not in (1,2,3,4) then raise exception 'Ders sayısı 1–4 arasında olmalı.'; end if;
  v_bit:=v_bas+(p_ders_sayisi*interval '1 hour'); if v_bit::date<>date '2000-01-01' then raise exception 'Ders saati gün sınırını aşıyor.'; end if; if p_ogrenci_birim_ucreti is null or p_ogrenci_birim_ucreti<0 or p_ogretmen_birim_hakedisi is null or p_ogretmen_birim_hakedisi<0 then raise exception 'Ücret ve hakediş geçerli olmalıdır.'; end if; if p_program_durumu not in ('Aktif','Pasif') then raise exception 'Geçersiz program durumu.'; end if; if v_tekrar not in ('Her Hafta','2 Haftada Bir','Ayda Bir') then raise exception 'Geçersiz tekrar sıklığı.'; end if; if v_tekrar<>'Her Hafta' and p_baslangic_tarihi is null then raise exception 'Bu tekrar sıklığı için başlangıç tarihi zorunludur.'; end if; if p_bitis_tarihi is not null and p_baslangic_tarihi is not null and p_bitis_tarihi<p_baslangic_tarihi then raise exception 'Bitiş tarihi başlangıç tarihinden önce olamaz.'; end if;
  if not exists(select 1 from public.ogrenciler where ogrenci_id=p_ogrenci_id and coalesce(durum,'Aktif')<>'Pasif') then raise exception 'Aktif öğrenci bulunamadı.'; end if; if not exists(select 1 from public.ogretmenler where ogretmen_id=p_ogretmen_id and coalesce(durum,'Aktif')<>'Pasif') then raise exception 'Aktif öğretmen bulunamadı.'; end if; if not exists(select 1 from public.branslar where brans_id=p_brans_id and coalesce(aktif,true)) then raise exception 'Aktif branş bulunamadı.'; end if; if not private.ogretmen_brans_uygun_mu(p_ogretmen_id,p_brans_id) then raise exception 'Seçilen öğretmen bu branş için tanımlı değil.'; end if; if not exists(select 1 from public.derslikler where derslik_id=p_derslik_id and coalesce(aktif,true)) then raise exception 'Aktif derslik bulunamadı.'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('bs_sabit_program_kaydet_v4')); select exists(select 1 from public.sabit_ders_programi where program_id=p_program_id) into v_program_var_mi;
  if p_program_durumu='Aktif' then v_kontrol:=public.sabit_program_cakisma_kontrol_v1(p_ogrenci_id,p_ogretmen_id,p_derslik_id,p_haftanin_gunu,p_baslangic_saati,p_ders_sayisi,v_tekrar,p_baslangic_tarihi,p_bitis_tarihi,p_program_id); if not coalesce((v_kontrol->>'uygun')::boolean,false) then raise exception '%',coalesce(v_kontrol->>'mesaj','Sabit program çakışıyor.'); end if; end if;
  insert into public.sabit_ders_programi(program_id,ogrenci_id,ogretmen_id,brans_id,derslik_id,haftanin_gunu,baslangic_saati,ders_sayisi,ogrenci_birim_ucreti,ogretmen_birim_hakedisi,baslangic_tarihi,bitis_tarihi,aktif,program_durumu,aciklama,kaynak_sistem,senkron_zamani,tekrar_sikligi) values(p_program_id,p_ogrenci_id,p_ogretmen_id,p_brans_id,p_derslik_id,p_haftanin_gunu,p_baslangic_saati,p_ders_sayisi,p_ogrenci_birim_ucreti,p_ogretmen_birim_hakedisi,p_baslangic_tarihi,p_bitis_tarihi,p_program_durumu='Aktif',p_program_durumu,nullif(trim(coalesce(p_aciklama,'')),''),'BS Eğitim PWA',pg_catalog.now(),v_tekrar) on conflict(program_id) do update set ogrenci_id=excluded.ogrenci_id,ogretmen_id=excluded.ogretmen_id,brans_id=excluded.brans_id,derslik_id=excluded.derslik_id,haftanin_gunu=excluded.haftanin_gunu,baslangic_saati=excluded.baslangic_saati,ders_sayisi=excluded.ders_sayisi,ogrenci_birim_ucreti=excluded.ogrenci_birim_ucreti,ogretmen_birim_hakedisi=excluded.ogretmen_birim_hakedisi,baslangic_tarihi=excluded.baslangic_tarihi,bitis_tarihi=excluded.bitis_tarihi,aktif=excluded.aktif,program_durumu=excluded.program_durumu,aciklama=excluded.aciklama,kaynak_sistem=excluded.kaynak_sistem,senkron_zamani=pg_catalog.now(),tekrar_sikligi=excluded.tekrar_sikligi;
  return jsonb_build_object('basarili',true,'program_id',p_program_id,'yeni_program',not v_program_var_mi,'tekrar_sikligi',v_tekrar,'guncellenen_gelecek_ders',0,'korunan_gelecek_ders',0,'korunan_istisna',0,'gecmis_dersler_korundu',true,'manuel_hafta_hazirlama',true,'cakisma_kontrolu',coalesce(v_kontrol,jsonb_build_object('uygun',true)));
end;
$function$;

create or replace function public.sabit_program_oneri_v1(p_ogrenci_id text,p_ogretmen_id text,p_derslik_id text,p_haftanin_gunu text,p_baslangic_saati time without time zone,p_ders_sayisi numeric,p_tekrar_sikligi text,p_baslangic_tarihi date,p_bitis_tarihi date,p_haric_program_id text default null::text)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_kontrol jsonb; v_room record; v_room_check jsonb; v_offset integer; v_candidate time; v_time_check jsonb; v_room_type text; v_rooms jsonb:='[]'::jsonb; v_times jsonb:='[]'::jsonb; v_count integer:=0; v_mesaj text;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if; v_kontrol:=public.sabit_program_cakisma_kontrol_v1(p_ogrenci_id,p_ogretmen_id,p_derslik_id,p_haftanin_gunu,p_baslangic_saati,p_ders_sayisi,p_tekrar_sikligi,p_baslangic_tarihi,p_bitis_tarihi,p_haric_program_id); if coalesce((v_kontrol->>'uygun')::boolean,false) then return v_kontrol||jsonb_build_object('onerilen_derslikler',v_rooms,'onerilen_saatler',v_times); end if;
  select mekan_turu into v_room_type from public.derslikler where derslik_id=p_derslik_id and coalesce(aktif,true);
  for v_room in select d.derslik_id,d.mekan_adi,d.mekan_turu from public.derslikler d where coalesce(d.aktif,true) and d.derslik_id<>p_derslik_id and case when v_room_type='Online' then d.mekan_turu='Online' when v_room_type='Ev' then d.mekan_turu='Ev' else coalesce(d.mekan_turu,'') not in ('Online','Ev') end order by case when d.mekan_turu=v_room_type then 0 else 1 end,d.mekan_adi loop v_room_check:=public.sabit_program_cakisma_kontrol_v1(p_ogrenci_id,p_ogretmen_id,v_room.derslik_id,p_haftanin_gunu,p_baslangic_saati,p_ders_sayisi,p_tekrar_sikligi,p_baslangic_tarihi,p_bitis_tarihi,p_haric_program_id); if coalesce((v_room_check->>'uygun')::boolean,false) then v_rooms:=v_rooms||jsonb_build_array(jsonb_build_object('derslik_id',v_room.derslik_id,'derslik',v_room.mekan_adi,'saat',to_char(p_baslangic_saati,'HH24:MI'))); v_count:=v_count+1; exit when v_count>=3; end if; end loop;
  v_count:=0; foreach v_offset in array array[-1,1,-2,2,-3,3,-4,4,-5,5,-6,6] loop v_candidate:=p_baslangic_saati+(v_offset*interval '30 minutes'); if (p_baslangic_saati+(v_offset*interval '30 minutes'))::time=p_baslangic_saati then continue; end if; if (date '2000-01-01'+v_candidate+(p_ders_sayisi*interval '1 hour'))::date<>date '2000-01-01' then continue; end if; v_time_check:=public.sabit_program_cakisma_kontrol_v1(p_ogrenci_id,p_ogretmen_id,p_derslik_id,p_haftanin_gunu,v_candidate,p_ders_sayisi,p_tekrar_sikligi,p_baslangic_tarihi,p_bitis_tarihi,p_haric_program_id); if coalesce((v_time_check->>'uygun')::boolean,false) then select mekan_adi into v_mesaj from public.derslikler where derslik_id=p_derslik_id; v_times:=v_times||jsonb_build_array(jsonb_build_object('saat',to_char(v_candidate,'HH24:MI'),'derslik_id',p_derslik_id,'derslik',v_mesaj)); v_count:=v_count+1; else for v_room in select d.derslik_id,d.mekan_adi,d.mekan_turu from public.derslikler d where coalesce(d.aktif,true) and d.derslik_id<>p_derslik_id and case when v_room_type='Online' then d.mekan_turu='Online' when v_room_type='Ev' then d.mekan_turu='Ev' else coalesce(d.mekan_turu,'') not in ('Online','Ev') end order by case when d.mekan_turu=v_room_type then 0 else 1 end,d.mekan_adi loop v_time_check:=public.sabit_program_cakisma_kontrol_v1(p_ogrenci_id,p_ogretmen_id,v_room.derslik_id,p_haftanin_gunu,v_candidate,p_ders_sayisi,p_tekrar_sikligi,p_baslangic_tarihi,p_bitis_tarihi,p_haric_program_id); if coalesce((v_time_check->>'uygun')::boolean,false) then v_times:=v_times||jsonb_build_array(jsonb_build_object('saat',to_char(v_candidate,'HH24:MI'),'derslik_id',v_room.derslik_id,'derslik',v_room.mekan_adi)); v_count:=v_count+1; exit; end if; end loop; end if; exit when v_count>=4; end loop;
  v_mesaj:=case when coalesce((v_kontrol->>'ogrenci_cakisma')::boolean,false) then 'Öğrenci seçilen saatte başka sabit derste.' when coalesce((v_kontrol->>'ogretmen_cakisma')::boolean,false) then 'Öğretmen seçilen saatte başka sabit derste.' when coalesce((v_kontrol->>'derslik_dolu')::boolean,false) then 'Seçilen derslik bu saatte dolu.' else coalesce(v_kontrol->>'mesaj','Program çakışması bulundu.') end;
  return v_kontrol||jsonb_build_object('mesaj',v_mesaj,'onerilen_derslikler',v_rooms,'onerilen_saatler',v_times);
end;
$function$;

create or replace function public.sabit_program_onizleme_v1(p_program_id text,p_baslangic date default current_date,p_adet integer default 8)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_program public.sabit_ders_programi%rowtype; v_bas date; v_adet integer:=greatest(1,least(coalesce(p_adet,8),24)); v_gun integer; v_tarihler jsonb;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if; select * into v_program from public.sabit_ders_programi where program_id=p_program_id; if not found then raise exception 'Sabit program bulunamadı.'; end if; v_gun:=case v_program.haftanin_gunu when 'Pazartesi' then 1 when 'Salı' then 2 when 'Çarşamba' then 3 when 'Perşembe' then 4 when 'Cuma' then 5 when 'Cumartesi' then 6 when 'Pazar' then 7 else null end; if v_gun is null then raise exception 'Programın haftanın günü geçersiz.'; end if; v_bas:=greatest(coalesce(p_baslangic,current_date),coalesce(v_program.baslangic_tarihi,'1900-01-01'::date));
  with aday as (select gs::date tarih from generate_series(v_bas::timestamp,(v_bas+interval '730 days')::timestamp,interval '1 day') gs where extract(isodow from gs)=v_gun and (v_program.bitis_tarihi is null or gs::date<=v_program.bitis_tarihi) and private.sabit_program_tarihe_duser_mi(v_program.tekrar_sikligi,v_program.baslangic_tarihi,gs::date) and not exists(select 1 from public.sabit_program_istisnalari i where i.program_id=v_program.program_id and i.orijinal_tarih=gs::date and i.iptal_mi=false) order by gs limit v_adet) select coalesce(jsonb_agg(jsonb_build_object('tarih',tarih,'gun',case extract(isodow from tarih) when 1 then 'Pazartesi' when 2 then 'Salı' when 3 then 'Çarşamba' when 4 then 'Perşembe' when 5 then 'Cuma' when 6 then 'Cumartesi' when 7 then 'Pazar' end,'saat',v_program.baslangic_saati,'ders_sayisi',v_program.ders_sayisi) order by tarih),'[]'::jsonb) into v_tarihler from aday;
  return jsonb_build_object('basarili',true,'program_id',v_program.program_id,'tekrar_sikligi',coalesce(v_program.tekrar_sikligi,'Her Hafta'),'haftanin_gunu',v_program.haftanin_gunu,'baslangic_tarihi',v_program.baslangic_tarihi,'bitis_tarihi',v_program.bitis_tarihi,'tarihler',v_tarihler);
end;
$function$;

create or replace function public.sabit_program_tek_sefer_tasi_guvenli_v1(p_program_id text,p_orijinal_tarih date,p_yeni_tarih date,p_yeni_baslangic_saati time without time zone,p_yeni_derslik_id text default null::text,p_aciklama text default null::text)
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_email text:=coalesce(auth.jwt()->>'email',auth.uid()::text,'BS Eğitim'); v_program public.sabit_ders_programi%rowtype; v_istisna public.sabit_program_istisnalari%rowtype; v_orijinal public.dersler%rowtype; v_kontrol jsonb; v_derslik text; v_mekan text; v_yeni_id text; v_bit timestamp;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if; if p_yeni_tarih is null or p_yeni_baslangic_saati is null then raise exception 'Yeni tarih ve saat zorunludur.'; end if; select * into v_program from public.sabit_ders_programi where program_id=p_program_id and program_durumu='Aktif'; if not found then raise exception 'Aktif sabit program bulunamadı.'; end if; if not private.sabit_program_tarih_uygun_mu(p_program_id,p_orijinal_tarih) then raise exception 'Orijinal tarih bu sabit programın doğal ders tarihi değil.'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('bs_istisna:'||p_program_id||':'||p_orijinal_tarih::text)); select * into v_istisna from public.sabit_program_istisnalari where program_id=p_program_id and orijinal_tarih=p_orijinal_tarih and iptal_mi=false limit 1; if found then return jsonb_build_object('basarili',true,'tekrar',true,'istisna_id',v_istisna.istisna_id,'tur',v_istisna.tur,'yeni_ders_id',v_istisna.yeni_ders_id); end if;
  select * into v_orijinal from public.dersler where program_id=p_program_id and tarih=p_orijinal_tarih order by olusturulma_zamani desc nulls last limit 1 for update; if found and coalesce(v_orijinal.ders_durumu,'Planlandı') not in ('Planlandı','İptal') then raise exception 'Orijinal ders artık planlama aşamasında değil; taşınamaz.'; end if;
  v_derslik:=coalesce(nullif(trim(coalesce(p_yeni_derslik_id,'')),''),v_program.derslik_id); v_kontrol:=public.ders_cakisma_kontrol_v1(p_yeni_tarih,v_program.ogrenci_id,v_program.ogretmen_id,v_derslik,p_yeni_baslangic_saati,v_program.ders_sayisi,case when found then v_orijinal.ders_id else null end); if not coalesce((v_kontrol->>'uygun')::boolean,false) then raise exception 'Yeni tarih/saat uygun değil: öğrenci, öğretmen veya derslik çakışması var.'; end if; select mekan_adi into v_mekan from public.derslikler where derslik_id=v_derslik and coalesce(aktif,true); if v_mekan is null then raise exception 'Aktif derslik bulunamadı.'; end if; v_bit:=p_yeni_tarih::timestamp+p_yeni_baslangic_saati+(v_program.ders_sayisi*interval '1 hour');
  if found and coalesce(v_orijinal.ders_durumu,'Planlandı')='Planlandı' then update public.dersler set ders_durumu='İptal',aciklama=concat_ws(' · ',nullif(aciklama,''),'Sabit program: tek seferlik başka tarihe taşındı'),son_degistiren=v_email,son_degistirme_zamani=now() where ders_id=v_orijinal.ders_id; end if;
  loop v_yeni_id:=substr(replace(gen_random_uuid()::text,'-',''),1,8); exit when not exists(select 1 from public.dersler where ders_id=v_yeni_id); end loop;
  insert into public.dersler(ders_id,program_id,tarih,ogrenci_id,ogretmen_id,brans_id,derslik_id,ders_sayisi,ogrenci_birim_ucreti,ogretmen_birim_hakedisi,ogrenci_toplam_tutar,ogretmen_toplam_hakedis,ders_durumu,aciklama,olusturan,olusturulma_zamani,baslangic_saati,bitis_saati,ders_turu,ders_yeri) values(v_yeni_id,null,p_yeni_tarih,v_program.ogrenci_id,v_program.ogretmen_id,v_program.brans_id,v_derslik,v_program.ders_sayisi,v_program.ogrenci_birim_ucreti,v_program.ogretmen_birim_hakedisi,coalesce(v_program.ogrenci_birim_ucreti,0)*v_program.ders_sayisi,coalesce(v_program.ogretmen_birim_hakedisi,0)*v_program.ders_sayisi,'Planlandı',concat_ws(' · ',nullif(trim(coalesce(p_aciklama,'')),''),'Sabit programdan taşındı: '||p_orijinal_tarih::text),v_email,now(),p_yeni_baslangic_saati,v_bit::time,'Tek Seferlik Değişiklik',v_mekan);
  insert into public.sabit_program_istisnalari(program_id,orijinal_tarih,tur,orijinal_ders_id,yeni_ders_id,aciklama,olusturan) values(p_program_id,p_orijinal_tarih,'Taşı',case when found then v_orijinal.ders_id else null end,v_yeni_id,nullif(trim(coalesce(p_aciklama,'')),''),v_email) returning * into v_istisna;
  return jsonb_build_object('basarili',true,'tekrar',false,'istisna_id',v_istisna.istisna_id,'tur','Taşı','orijinal_ders_id',v_istisna.orijinal_ders_id,'yeni_ders_id',v_yeni_id,'cakisma_kontrolu',v_kontrol);
end;
$function$;

create or replace function public.sistem_saglik_kontrolu_v1()
returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_hatali_program_brans integer; v_gecersiz_tekrar_program integer; v_hatali_ders_toplam integer; v_mukerrer_program_ders integer; v_tahsilat_kasa_eksik integer; v_ogretmen_odeme_kasa_eksik integer; v_gider_kasa_eksik integer; v_tahsilat_iptal_kasa_aktif integer; v_ogretmen_odeme_iptal_kasa_aktif integer; v_gider_iptal_kasa_aktif integer; v_yetim_ders integer; v_toplam_hata integer;
begin
  if auth.uid() is null or not private.bs_ofis_yonetici_mi() then raise exception 'Bu işlem için yönetici yetkisi gerekir.'; end if;
  select count(*) into v_hatali_program_brans from public.sabit_ders_programi p where p.program_durumu='Aktif' and not private.ogretmen_brans_uygun_mu(p.ogretmen_id,p.brans_id);
  select count(*) into v_gecersiz_tekrar_program from public.sabit_ders_programi p where p.program_durumu='Aktif' and (coalesce(nullif(trim(p.tekrar_sikligi),''),'Her Hafta') not in ('Her Hafta','2 Haftada Bir','Ayda Bir') or (coalesce(nullif(trim(p.tekrar_sikligi),''),'Her Hafta') in ('2 Haftada Bir','Ayda Bir') and p.baslangic_tarihi is null) or (p.bitis_tarihi is not null and p.baslangic_tarihi is not null and p.bitis_tarihi<p.baslangic_tarihi));
  select count(*) into v_hatali_ders_toplam from public.dersler d where abs(coalesce(d.ogrenci_toplam_tutar,0)-coalesce(d.ogrenci_birim_ucreti,0)*coalesce(d.ders_sayisi,0))>0.01 or abs(coalesce(d.ogretmen_toplam_hakedis,0)-coalesce(d.ogretmen_birim_hakedisi,0)*coalesce(d.ders_sayisi,0))>0.01;
  select count(*) into v_mukerrer_program_ders from (select program_id,tarih from public.dersler where program_id is not null group by program_id,tarih having count(*)>1) x;
  select count(*) into v_tahsilat_kasa_eksik from public.tahsilatlar t where coalesce(t.iptal_mi,false)=false and not exists(select 1 from public.kasa_hareketleri k where k.kaynak_turu='Tahsilat' and k.kaynak_id=t.tahsilat_id and coalesce(k.iptal_mi,false)=false and k.hareket_turu='Gelir' and abs(k.tutar-t.tutar)<=0.01);
  select count(*) into v_ogretmen_odeme_kasa_eksik from public.ogretmen_odemeleri o where coalesce(o.iptal_mi,false)=false and not exists(select 1 from public.kasa_hareketleri k where k.kaynak_turu='Öğretmen Ödemesi' and k.kaynak_id=o.ogretmen_odeme_id and coalesce(k.iptal_mi,false)=false and k.hareket_turu='Gider' and abs(k.tutar-o.tutar)<=0.01);
  select count(*) into v_gider_kasa_eksik from public.giderler g where coalesce(g.iptal_mi,false)=false and not exists(select 1 from public.kasa_hareketleri k where k.kaynak_turu='Gider' and k.kaynak_id=g.gider_id and coalesce(k.iptal_mi,false)=false and k.hareket_turu='Gider' and abs(k.tutar-g.tutar)<=0.01);
  select count(*) into v_tahsilat_iptal_kasa_aktif from public.tahsilatlar t where coalesce(t.iptal_mi,false)=true and exists(select 1 from public.kasa_hareketleri k where k.kaynak_turu='Tahsilat' and k.kaynak_id=t.tahsilat_id and coalesce(k.iptal_mi,false)=false);
  select count(*) into v_ogretmen_odeme_iptal_kasa_aktif from public.ogretmen_odemeleri o where coalesce(o.iptal_mi,false)=true and exists(select 1 from public.kasa_hareketleri k where k.kaynak_turu='Öğretmen Ödemesi' and k.kaynak_id=o.ogretmen_odeme_id and coalesce(k.iptal_mi,false)=false);
  select count(*) into v_gider_iptal_kasa_aktif from public.giderler g where coalesce(g.iptal_mi,false)=true and exists(select 1 from public.kasa_hareketleri k where k.kaynak_turu='Gider' and k.kaynak_id=g.gider_id and coalesce(k.iptal_mi,false)=false);
  select count(*) into v_yetim_ders from public.dersler d where (d.ogrenci_id is not null and not exists(select 1 from public.ogrenciler o where o.ogrenci_id=d.ogrenci_id)) or (d.ogretmen_id is not null and not exists(select 1 from public.ogretmenler o where o.ogretmen_id=d.ogretmen_id)) or (d.brans_id is not null and not exists(select 1 from public.branslar b where b.brans_id=d.brans_id)) or (d.derslik_id is not null and not exists(select 1 from public.derslikler l where l.derslik_id=d.derslik_id));
  v_toplam_hata:=v_hatali_program_brans+v_gecersiz_tekrar_program+v_hatali_ders_toplam+v_mukerrer_program_ders+v_tahsilat_kasa_eksik+v_ogretmen_odeme_kasa_eksik+v_gider_kasa_eksik+v_tahsilat_iptal_kasa_aktif+v_ogretmen_odeme_iptal_kasa_aktif+v_gider_iptal_kasa_aktif+v_yetim_ders;
  return jsonb_build_object('basarili',v_toplam_hata=0,'toplam_hata',v_toplam_hata,'kontrol_zamani',now(),'hatali_program_brans',v_hatali_program_brans,'gecersiz_tekrar_program',v_gecersiz_tekrar_program,'hatali_ders_toplam',v_hatali_ders_toplam,'mukerrer_program_ders',v_mukerrer_program_ders,'tahsilat_kasa_eksik',v_tahsilat_kasa_eksik,'ogretmen_odeme_kasa_eksik',v_ogretmen_odeme_kasa_eksik,'gider_kasa_eksik',v_gider_kasa_eksik,'tahsilat_iptal_kasa_aktif',v_tahsilat_iptal_kasa_aktif,'ogretmen_odeme_iptal_kasa_aktif',v_ogretmen_odeme_iptal_kasa_aktif,'gider_iptal_kasa_aktif',v_gider_iptal_kasa_aktif,'yetim_ders',v_yetim_ders);
end;
$function$;
