from pathlib import Path


def replace_once(path, old, new):
    p=Path(path)
    text=p.read_text()
    count=text.count(old)
    if count!=1:
        raise SystemExit(f'{path}: beklenen blok {count} kez bulundu')
    p.write_text(text.replace(old,new,1))

for path, mode in [('src/pages/CalendarPage.tsx','calendar'),('src/pages/DailyCalendarPage.tsx','daily')]:
    p=Path(path)
    text=p.read_text()
    if mode=='calendar':
        old='''    <section className="page-title-row"><div className="calendar-title-copy"><span className="eyebrow">DERS PROGRAMI</span><div className="calendar-title-line"><h1>Program</h1><button className="primary-btn calendar-title-week-action" disabled={isPastWeek||weekBusy||weekStatusBusy||weekReady} onClick={()=>void prepareWeek()}><CalendarCheck2 size={17}/>{weekActionText}</button></div></div></section>\n\n    <section className="calendar-week-toolbar" aria-label="Program hafta gezintisi">\n      <button className="calendar-mode-btn" type="button" onClick={()=>nav('/takvim/gunluk')}><CalendarDays size={16}/>Takvim</button>\n      <div className="calendar-week-range-compact"><b>{compactWeekRange(monday,addDays(monday,6))}</b></div>\n      <div className="calendar-week-nav-compact" role="group" aria-label="Hafta değiştir">'''
        new='''    <section className="page-title-row"><div className="calendar-title-copy"><span className="eyebrow">DERS PROGRAMI</span><div className="calendar-title-line calendar-title-line-with-range"><h1>Program</h1><div className="calendar-title-week-range"><b>{compactWeekRange(monday,addDays(monday,6))}</b></div><button className="primary-btn calendar-title-week-action" disabled={isPastWeek||weekBusy||weekStatusBusy||weekReady} onClick={()=>void prepareWeek()}><CalendarCheck2 size={17}/>{weekActionText}</button></div></div></section>\n\n    <section className="calendar-week-toolbar" aria-label="Program hafta gezintisi">\n      <button className="calendar-mode-btn" type="button" onClick={()=>nav('/takvim/gunluk')}><CalendarDays size={16}/>Takvim</button>\n      <div className="calendar-week-nav-compact" role="group" aria-label="Hafta değiştir">'''
    else:
        old='''    <section className="page-title-row"><div className="calendar-title-copy"><span className="eyebrow">DERS PROGRAMI</span><div className="calendar-title-line"><h1>Program</h1><button className="primary-btn calendar-title-week-action" disabled={isPastWeek||weekBusy||weekStatusBusy||weekReady} onClick={()=>void prepareWeek()}><CalendarCheck2 size={17}/>{weekActionText}</button></div></div></section>\n\n    <section className="calendar-week-toolbar" aria-label="Program hafta gezintisi">\n      <button className="calendar-mode-btn" type="button" onClick={()=>nav('/takvim')}><List size={16}/>Liste</button>\n      <div className="calendar-week-range-compact"><b>{compactWeekRange(monday,addDays(monday,6))}</b></div>\n      <div className="calendar-week-nav-compact" role="group" aria-label="Hafta değiştir">'''
        new='''    <section className="page-title-row"><div className="calendar-title-copy"><span className="eyebrow">DERS PROGRAMI</span><div className="calendar-title-line calendar-title-line-with-range"><h1>Program</h1><div className="calendar-title-week-range"><b>{compactWeekRange(monday,addDays(monday,6))}</b></div><button className="primary-btn calendar-title-week-action" disabled={isPastWeek||weekBusy||weekStatusBusy||weekReady} onClick={()=>void prepareWeek()}><CalendarCheck2 size={17}/>{weekActionText}</button></div></div></section>\n\n    <section className="calendar-week-toolbar" aria-label="Program hafta gezintisi">\n      <button className="calendar-mode-btn" type="button" onClick={()=>nav('/takvim')}><List size={16}/>Liste</button>\n      <div className="calendar-week-nav-compact" role="group" aria-label="Hafta değiştir">'''
    if text.count(old)!=1:
        raise SystemExit(f'{path}: üst blok {text.count(old)} kez bulundu')
    p.write_text(text.replace(old,new,1))

css_path=Path('src/program-share.css')
css=css_path.read_text()
old='''.calendar-title-line{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0}\n.calendar-title-line h1{min-width:0}\n.calendar-title-week-action{\n  flex:0 0 auto;min-height:38px;max-width:58%;padding:6px 11px;\n  font-size:9.5px;line-height:1.15;text-align:center;box-shadow:0 5px 12px rgba(37,99,235,.14);\n}\n.calendar-title-week-action svg{flex:0 0 auto}\n\n.calendar-week-toolbar{display:grid;grid-template-columns:auto minmax(62px,1fr) auto;align-items:center;gap:8px;min-width:0}\n.calendar-week-toolbar .calendar-mode-btn{min-height:38px;padding:6px 10px;font-size:10.5px;white-space:nowrap}\n.calendar-week-range-compact{min-width:0;text-align:center;color:#475569;font-size:12px;font-weight:900;white-space:nowrap}\n.calendar-week-nav-compact{display:grid;grid-template-columns:30px auto 30px;align-items:center;gap:3px;padding:3px;background:#eef2f7;border:1px solid #e2e8f0;border-radius:12px}\n.calendar-week-nav-compact button{height:32px;min-width:30px;padding:0 7px;border:0;border-radius:9px;background:transparent;color:#475569;font-size:10px;font-weight:900;cursor:pointer;white-space:nowrap}\n'''
new='''.calendar-title-line{display:flex;align-items:center;justify-content:space-between;gap:12px;min-width:0}\n.calendar-title-line h1{min-width:0}\n.calendar-title-line-with-range{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center}\n.calendar-title-line-with-range h1{justify-self:start}\n.calendar-title-week-range{justify-self:center;min-width:0;color:#475569;font-size:12px;font-weight:900;white-space:nowrap}\n.calendar-title-week-action{\n  flex:0 0 auto;justify-self:end;min-height:38px;max-width:58%;padding:6px 11px;\n  font-size:9.5px;line-height:1.15;text-align:center;box-shadow:0 5px 12px rgba(37,99,235,.14);\n}\n.calendar-title-week-action svg{flex:0 0 auto}\n\n.calendar-week-toolbar{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:8px;min-width:0}\n.calendar-week-toolbar .calendar-mode-btn{min-height:38px;padding:6px 10px;font-size:10.5px;white-space:nowrap;justify-self:start}\n.calendar-week-nav-compact{display:grid;grid-template-columns:30px 82px 30px;align-items:center;gap:3px;padding:3px;background:#eef2f7;border:1px solid #e2e8f0;border-radius:12px;justify-self:end}\n.calendar-week-nav-compact button{height:32px;min-width:30px;padding:0 7px;border:0;border-radius:9px;background:transparent;color:#475569;font-size:10px;font-weight:900;cursor:pointer;white-space:nowrap}\n'''
if css.count(old)!=1:
    raise SystemExit(f'program-share.css ana blok {css.count(old)} kez bulundu')
css=css.replace(old,new,1)
old_mobile='''  .calendar-title-line{gap:8px}\n  .calendar-title-week-action{min-height:36px;max-width:60%;padding:5px 9px;font-size:9px;gap:5px}\n  .calendar-title-week-action svg{width:15px;height:15px}\n  .calendar-week-toolbar{gap:6px}\n  .calendar-week-toolbar .calendar-mode-btn{min-height:36px;padding:5px 8px;font-size:9.5px;gap:5px}\n  .calendar-week-toolbar .calendar-mode-btn svg{width:15px;height:15px}\n  .calendar-week-range-compact{font-size:10.5px}\n  .calendar-week-nav-compact{grid-template-columns:28px auto 28px;gap:2px;padding:3px}\n  .calendar-week-nav-compact button{height:30px;min-width:28px;padding:0 5px;font-size:9.5px}\n'''
new_mobile='''  .calendar-title-line{gap:8px}\n  .calendar-title-line-with-range{grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:6px}\n  .calendar-title-week-range{font-size:10.5px}\n  .calendar-title-week-action{min-height:36px;max-width:100%;padding:5px 9px;font-size:9px;gap:5px}\n  .calendar-title-week-action svg{width:15px;height:15px}\n  .calendar-week-toolbar{gap:6px}\n  .calendar-week-toolbar .calendar-mode-btn{min-height:36px;padding:5px 8px;font-size:9.5px;gap:5px}\n  .calendar-week-toolbar .calendar-mode-btn svg{width:15px;height:15px}\n  .calendar-week-nav-compact{grid-template-columns:28px 76px 28px;gap:2px;padding:3px}\n  .calendar-week-nav-compact button{height:30px;min-width:28px;padding:0 5px;font-size:9.5px}\n'''
if css.count(old_mobile)!=1:
    raise SystemExit(f'program-share.css mobil blok {css.count(old_mobile)} kez bulundu')
css_path.write_text(css.replace(old_mobile,new_mobile,1))

test_path=Path('scripts/check-calendar-ux.mjs')
test=test_path.read_text()
old_test="  ['Program ve günlük Takvim tek satırlık kompakt hafta çubuğunu kullanır',[calendar,dailyCalendar].every(src=>src.includes('className=\"calendar-week-toolbar\"')&&src.includes('compactWeekRange(monday,addDays(monday,6))')&&!src.includes('className=\"week-switcher\"'))],\n"
new_test="  ['Program ve günlük Takvim tarih aralığını başlık satırının ortasında gösterir',[calendar,dailyCalendar].every(src=>src.includes('calendar-title-line calendar-title-line-with-range')&&src.includes('className=\"calendar-title-week-range\"')&&src.includes('compactWeekRange(monday,addDays(monday,6))')&&src.indexOf('calendar-title-week-range')<src.indexOf('calendar-week-toolbar'))],\n  ['Program ve günlük Takvim alt satırda yalnız görünüm ve kompakt hafta gezintisini kullanır',[calendar,dailyCalendar].every(src=>src.includes('className=\"calendar-week-toolbar\"')&&src.includes('className=\"calendar-week-nav-compact\"')&&!src.includes('className=\"week-switcher\"')&&!src.includes('calendar-week-range-compact'))],\n"
if test.count(old_test)!=1:
    raise SystemExit(f'check-calendar-ux hedef test {test.count(old_test)} kez bulundu')
test=test.replace(old_test,new_test,1)
old_css_test="  ['Kompakt hafta çubuğu tek satırdır ve Bu Hafta vurgusu korunur',programCss.includes('.calendar-week-toolbar{display:grid')&&programCss.includes('.calendar-week-nav-compact')&&programCss.includes('.calendar-week-nav-compact button.active{background:#2563eb;color:#fff')],\n"
if old_css_test in test:
    new_css_test="  ['Kompakt hafta çubuğu tek satırdır, tarih başlıktadır ve Bu Hafta daha geniştir',programCss.includes('.calendar-title-line-with-range{display:grid')&&programCss.includes('.calendar-title-week-range')&&programCss.includes('grid-template-columns:30px 82px 30px')&&programCss.includes('grid-template-columns:28px 76px 28px')&&programCss.includes('.calendar-week-nav-compact button.active{background:#2563eb;color:#fff')],\n"
    test=test.replace(old_css_test,new_css_test,1)
test_path.write_text(test)
